.eslintignore
packages/next-router/.toolkitrc.yml
packages/next-router/package.json
packages/next-router/src/index.ts
packages/next-router/src/tasks/next-router.ts
packages/next-router/src/types/ft-next-router.d.ts
packages/next-router/tsconfig.json
packages/node/.toolkitrc.yml
packages/node/package.json
packages/node/src/index.ts
packages/node/src/tasks/node.ts
packages/node/tsconfig.json
packages/sandbox/.toolkitrc.yml
packages/sandbox/package.json
packages/sandbox/server/app.js
packages/state/src/index.ts
packages/types/src/schema.ts
packages/types/src/schema/next-router.ts
packages/types/src/schema/node.ts
packages/vault/src/index.ts
tsconfig.json

adds a plugin to run a node app directly on the `run:local` hook. depends on #130. plugin is deliberately unconfigurable (apart from server entry point) for now. it's easy to add options but impossible to delete them.

CPP-620 add basic node plugin for running node things

---

.circleci/config.yml

Based on [this Slack conversation](https://financialtimes.slack.com/archives/C3TJ6KXEU/p1610989688007600) this should be the only work needed to set up the nightly build.

CPP-636 add nightly CircleCI build

---

orb/src/@orb.yml
orb/src/jobs/heroku-promote.yml
orb/src/jobs/setup.yml

This will post any heroku deployments in CircleCI to the [Change API](https://github.com/Financial-Times/change-api) so changes in services can be tracked.

Integrate change API orb into tool kit orb

---

packages/vault/jest.config.js
packages/vault/package.json
packages/vault/src/index.ts
packages/vault/test/index.test.ts
packages/vault/tsconfig.json

When `dotcom-tool-kit run:local` runs it uses the `vault` plugin to get the required environment variables for `next-router` and the app being developed. It needs an auth token to gain access, and first checks for an existing one in `~/.vault-token`. However, these tokens expire after 8 hours, and it's not checking whether this is a current token so fails with an authentication failure if it's using an expired token. 
This PR adds a check for an expired token, and requests a new one if found. It also writes any new tokens to file.

Local vault fix CPP-651

---

core/cli/test/__snapshots__/index.test.ts.snap
plugins/circleci/src/circleci-config.ts
plugins/circleci/src/index.ts
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/test/files/comment-without-hook/.circleci/config.yml
plugins/circleci/test/files/with-hook/.circleci/config.yml

[Ticket CPP-638](https://financialtimes.atlassian.net/browse/CPP-638)
This PR modifies the circleci plugin so that it:
- errors and asks user to recreate if `nightly` workflow is not present
- adds optional `addToNightly` property to the `CircleConfig` interface
- if `addToNightly` is set to **true** it will clone the `tool-kit` job, remove the `waiting-for-approval` requirement and add it to the `nightly` workflow
- sets the `addToNightly` property to **true** for `BuildCI` and `TestCI`
- fixes tests

CPP-638 add circleci nightly workflow to task

---

plugins/heroku/test/tasks/review.test.ts

Was getting `UnhandledPromiseRejection` warnings when running our test suite. Turns out this `Promise.resolve` was being created but not returned (and consequently not handled.) Return the other path as a promise as well to better mimic the behaviour of the `heroku-client` method we're mocking.

Fix unreturned promises from mock function

---

.circleci/config.yml
.eslintrc.js

we've got the plugin installed but aren't actually using any of its rules! this would have caught #53. this has a fair chance of causing some linting errors in CI which i'll fix in this branch if it does (writing this commit on github bc easier)

CPP-727 add eslint import plugin recommended config

---

core/create/src/index.ts
core/sandbox/package.json
docs/migrating-to-tool-kit.md
lib/types/package.json
lib/types/src/schema.ts
lib/types/src/schema/heroku.ts
plugins/heroku/src/scaleDyno.ts
plugins/heroku/src/tasks/production.ts
plugins/heroku/test/tasks/production.test.ts

Adds a new step to the `heroku:production` task that will scale the dyno to a value set in the `.toolkitrc.yml`. Will skip the step (leaving the dyno at its previous value) if no `scaling` option is set.
Would also have liked to added support for enabling autoscaling, but it seems that Heroku is using [undocumented API calls](https://github.com/heroku/cli/blob/4b89482ab15e28d1449af9cfe95821d64acd4b6e/packages/ps/src/commands/ps/autoscale/enable.ts#L64) to configure it. Other people have gone to the trouble of [documenting the behaviour](https://registry.terraform.io/providers/davidji99/herokux/latest/docs/resources/formation_autoscaling), but the documentation illustrates how flakey (and risky – if you set it up wrong you might be forced to delete and recreate your app config from scratch …

CP-666 Add option to scale heroku dynos

---

plugins/lint-staged-npm/src/index.ts

`lint-staged-npm` allows you to set the globs used by lint-staged in your `.toolkitrc.yml` config. Previously, it would read the options when the class was constructed. However, now that we construct the classes when first loading the plugins (in order to verify they're instances of the `Hook` class) this code is now running before the options from the config file have been set. Instead, lazily read the options the first time the key property is accessed, which should be just after the place where they were previously being constructed.
This should fix all `lint-staged-npm` hooks being assigned to the default `**/*.js` glob regardless of their `formatGlob` and `testGlob` options.

Fix ignored lint-staged-npm glob options

---

core/cli/package.json
core/create/src/index.ts
core/sandbox/.circleci/config.yml
core/sandbox/.toolkitrc.yml
core/sandbox/jest.config.js
core/sandbox/package.json
lib/package-json-hook/package.json
lib/types/package.json
lib/types/src/schema/jest.ts
package.json
plugins/circleci/package.json
plugins/eslint/package.json
plugins/jest/.toolkitrc.yml
plugins/jest/jest.config.js
plugins/jest/package.json
plugins/jest/src/index.ts
plugins/jest/src/run-jest.ts
plugins/jest/src/tasks/ci.ts
plugins/jest/src/tasks/local.ts
plugins/jest/tests/jest-plugin.test.ts
plugins/jest/tsconfig.json
plugins/mocha/package.json
plugins/n-test/package.json
plugins/prettier/package.json
plugins/upload-assets-to-s3/package.json
plugins/webpack/package.json
scripts/create-plugin.js
tsconfig.json

There is no well documented way run jest programmatically ([issue](https://github.com/facebook/jest/issues/5048)) so I have used the cli to run jest

CPP-733 Jest plugin

---

plugins/webpack/src/run-webpack.ts
plugins/webpack/test/tasks/webpack.test.ts

If configPath wasn't set we were instead falling back to inserting an empty string into the list of arguments to pass to webpack. Unfortunately, unlike on a terminal where empty space would typically be stripped, the empty string is still interpreted as an argument in this case (similar to how the empty string would be an argument if you ran `webpack ''` instead of `webpack  `) and by default is considered a path to the webpack config file, which then isn't found. The webpack error isn't particularly helpful so it went unnoticed.
As a bonus, also pass the `--color` option to webpack to force ANSI colours even though we're piping to winston.

CPP-771 Fix webpack failing if configPath option isn't set

---

plugins/backend-app/package.json

- Corrected the `main` field to point to the `index.js` script
- Don't filter out `index.js` from files included in the published package by removing the `files` field
- Delete the unused `@dotcom-tool-kit/types` dependency

CPP-770 Fix issues with published backend-app package

---

orb/src/jobs/build.yml

`build` will probably have generated some files that we need to keep for future jobs

persist workspace after build job

---

core/cli/package.json
lib/logger/package.json
lib/logger/src/helpers.ts
lib/logger/src/logger.ts
lib/package-json-hook/package.json
lib/types/package.json
lib/vault/package.json
lib/wait-for-ok/package.json
plugins/babel/package.json
plugins/circleci/package.json
plugins/eslint/package.json
plugins/heroku/package.json
plugins/jest/package.json
plugins/lint-staged/tsconfig.json
plugins/mocha/package.json
plugins/n-test/package.json
plugins/npm/package.json
plugins/prettier/package.json
plugins/upload-assets-to-s3/package.json
plugins/webpack/package.json

winston have now [issued a patch](https://github.com/winstonjs/winston/releases/tag/v3.5.1) that fixes the breaking type change that was inadvertently made in [version 3.5.0](https://github.com/winstonjs/winston/releases/tag/v3.5.0) though this, naturally, breaks the [changes](https://github.com/Financial-Times/dotcom-tool-kit/commit/663c89849ec967081caf2e73d0190e8fb759dc39) we made to accommodate that release...

Fix broken winston types in logger

---

package.json

Should significantly speed up the time it takes to run the hook, which would previously often run for upwards of 10 seconds every time a `git commit` was invoked. We don't need to run a whole lint each time; during a commit we only care about verifying the staged files. Other files may have issues but that's okay as we aren't committing them right now.

Only lint staged files in pre-commit hook

---

core/cli/test/__snapshots__/index.test.ts.snap
orb/src/jobs/setup.yml
plugins/circleci/src/circleci-config.ts
plugins/circleci/src/index.ts

During a nori run I noticed that currently `tool-kit/setup` does not require the `waiting-for-approval` job that optionally runs for nori branches, which instead only blocks the `tool-kit/build` job and onwards. This doesn't make much sense seeing as the `setup` job runs one of the most expensive operations in the CircleCI workflow – the `npm install` step – so really shouldn't be running until approved in order to reduce the load on the CI when we push a series of nori commits.

Don't run setup orb job until workflow is approved

---

plugins/heroku/src/promoteStagingToProduction.ts
plugins/heroku/src/setConfigVars.ts
plugins/heroku/src/tasks/review.ts
plugins/heroku/src/tasks/staging.ts
plugins/heroku/test/setConfigVars.test.ts
plugins/heroku/test/tasks/review.test.ts
plugins/heroku/test/tasks/staging.test.ts

Reverts Financial-Times/dotcom-tool-kit#171
I'm having trouble getting this to work, but, in any case, it still only runs in ci way after the review app is built. I think we need a different approach - possibly the review app running the equivalent of `make .env` in the heroku-postbuild. 
It needs to come out of main as it's blocking any releases.

Revert "cpp-778 update config vars on review apps at first possible moment"

---

.circleci/config.yml

for version tags with the `-beta.whatever` prerelease tags, exclude them from the main publish workflow, and publish them with a separate workflow that doesn't use the `latest` dist tag so they don't get picked up when doing `npm install dotcom-tool-kit@latest` or whatever

add workflow for releasing prereleases

---

core/cli/test/__snapshots__/index.test.ts.snap
plugins/circleci-heroku/src/index.ts

This is a workaround to the circleci bug that overwrites the state file when importing multiple workspaces

cpp-807 change the order of jobs to load workspaces correctly

---

core/sandbox/.toolkitrc.yml
core/sandbox/package.json
lib/logger/src/helpers.ts
lib/types/src/schema.ts
lib/types/src/schema/nodemon.ts
plugins/nodemon/.toolkitrc.yml
plugins/nodemon/package.json
plugins/nodemon/src/index.ts
plugins/nodemon/src/tasks/nodemon.ts
plugins/nodemon/tsconfig.json
tsconfig.json

This plugin provides a task that can be used in place of the Node plugin and will restart the running process if there are file changes in the directory or if the process exits unexpectedly. Will respect the configuration specified in a `nodemon.json` in `$CWD`, `$HOME`, or the location specified by the `configPath` option.
I figured there was big enough difference in code to justify splitting this out into a new module rather than just being an option you could toggle in a `.toolkitrc.yml`. Splitting the plugins also means that we do not force consumers to install the `nodemon` package when they just want to install the Node plugin.

CPP-782 Add nodemon plugin

---

.circleci/config.yml
package.json

Upgrade the repository to a newer version of Node now that Node 12 is approaching end-of-life. Seeing as Tool Kit is included in other projects we want to support both Node 16 and Node 14, as they are being used in Heroku and AWS apps respectively.

Update to Node 16 and test Node 14 in the CI

---

orb/src/jobs/build-test.yml

This is a workaround to avoid the toolkit state file being overwritten. Apps can use this job in their .circleci/config.yml job rather than build and test, as used in next-static [here](https://github.com/Financial-Times/next-static/blob/4cdf82ce537f30eaa0d646d0e0fadd236acf4b5c/.circleci/config.yml#L51-L62)

create build-test job to stop workspace persistence

---

core/cli/test/index.test.ts

to fix [this](https://app.circleci.com/pipelines/github/Financial-Times/dotcom-tool-kit/1189/workflows/bfd0e692-fbb0-4f51-b62f-4c877e4f24d6/jobs/4259) intermittent issue

increase timeout in core/cli/test/index.test.ts

---

package.json
plugins/circleci-npm/package.json
plugins/circleci-npm/test/index.test.ts
plugins/npm/test/npm-publish.test.ts

--runInBand makes tests run serially according to [docs](https://jestjs.io/docs/cli#--detectopenhandles), which allows the process to have more resources and therefore prevent the tests from being starved from resources and hang

added back test with runInBand

---

.gitignore
lib/state/src/index.ts

Currently we have one state file in toolkit - .toolkitstate.json in the project's root. This is causing a problem in circle ci, where multiple concurrent jobs are writing to the state file and persisting that to the next job. Where a job attaches both versions (via workspaces), the last copy overwrites the any others, thereby losing the state information.
This PR splits the state into different stages, thereby allowing for writes from multiple concurrent jobs/workspaces.

cpp-830 split state out into different files

---

orb/src/commands/persist-workspace.yml

Now that it's split out, we're going to need to persist the new state folder rather than the state file.

cpp-830 persist the state folder

---

core/cli/test/__snapshots__/index.test.ts.snap
plugins/circleci-npm/src/index.ts
plugins/npm/src/index.ts

tasks should only be exported from the plugin they're defined in

export publish task from npm not circleci-npm

---

lib/types/src/schema.ts
lib/types/src/schema/circleci.ts
plugins/circleci/src/circleci-config.ts
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/tsconfig.json

Now that we've migrated to newer Node versions we need to update CircleCI configs to use the correct Node version too. But seeing as both Node 14 and Node 16 should be supported we can't just hardcode one version (though that might cause upgrade issues down the road anyway!) So you can now set the Node version you want in the Tool Kit config, with the default being Node 16.

CPP-846 Allow Node version to be configured in CircleCI hook

---

plugins/backend-app/.toolkitrc.yml
plugins/backend-app/package.json

it won't necessarily be needed, and we don't have a good workflow in place for e.g. running it before starting the server or in watch mode, so remove it and let people configure it themselves

remove babel plugin from the backend-app preset

---

.circleci/config.yml

They were breaking release-please's ability to parse the arguments as the slashes were inadvertently being included.
_yaml_ **shakes fist**

Remove line delimeters from release-please command

---

orb/README.md
orb/src/@orb.yml
orb/src/jobs/build-test.yml
orb/src/jobs/build.yml
orb/src/jobs/e2e-test-review.yml
orb/src/jobs/e2e-test-staging.yml
orb/src/jobs/heroku-promote.yml
orb/src/jobs/heroku-provision.yml
orb/src/jobs/heroku-staging.yml
orb/src/jobs/publish.yml
orb/src/jobs/setup.yml
orb/src/jobs/test.yml

This includes bumping the default Node and npm versions used to Node 16 and npm 8. We also update to the latest version of the node orb and replace the removed `install-npm` job with a command to install npm ourselves.
(This is also an opportunity to bump the orb up to v2 that comes with our new semver commitments, as it wasn't included in the original commit releasing 2.0 versions of the packages because of https://github.com/googleapis/release-please/issues/1360)

Bump Node versions in orb

---

release-please-config.json

The package name is not inferred for `simple` packages (the `package.json` is read for `node` packages.) We need to specify the package name so that the correct git tag will be created when releasing.

Manually specify orb's component name

---

.gitignore
.npmrc
package-lock.json

Now that we aren't using athloi anymore it will be okay to include a lockfile. Seeing as this is an npm workspace, all the packages in the project share the same lockfile at the workspace root (along with sharing a `node_modules` directory)
This should help improve installation performance and make sure behaviour is consistent between installations.

Add a lockfile to the workspace

---

plugins/frontend-app/.toolkitrc.yml

We removed Babel from the `backend-app` plugin recently, but we defined a conflict resolution between it and the Webpack plugin for the `frontend-app` plugin which is now causing an error seeing as the Babel hooks are not present in the plugin anymore.

Don't include Babel in frontend-app config

---

.circleci/config.yml

I've seen some [build failures](https://app.circleci.com/pipelines/github/Financial-Times/dotcom-tool-kit/1419/workflows/0848a4d4-2214-4f35-afd5-36366cc3ecd0/jobs/5999) in the CI since adding a lockfile and peer dependencies on `dotcom-tool-kit` that are fixed by using npm 8 rather than npm 7. I think this is a bug in npm's resolution logic that has now been fixed in later releases. It might be worth considering removing npm 7 from our `engines` field but seeing as it's pretty easy to get it working still (just deleting the lockfile does the trick) I think it would be better to leave it in.
Hopefully someone will make a Volta orb before I am forced to.

Use npm 8 in CI

---

package-lock.json
package.json

Fixes the issue described in https://github.com/googleapis/release-please/issues/1403 that is causing our release-please PRs to bump every plugin as they all have `dotcom-tool-kit` as a peer dependency, even though no code is actually changing in the component (nor should need to be changed.)

Use fork of release-please to fix peer dependency issue

---

core/cli/src/plugin.ts
core/cli/test/files/cousins/.toolkitrc.yml
core/cli/test/index.test.ts

currently, we only detect conflicts between sibling plugin hooks, e.g.:
```
├ webpack
╰ babel
```
would correctly raise a conflict, because both are assigning the `build:*` hooks by default.
if, however, the packages are not direct siblings but cousins:
```
├ frontend-app
│ ╰ webpack
╰ babel
```
that conflict wouldn't be noticed, and Tool Kit would silently choose whichever plugin was loaded last to run on that hook without requiring conflict resolution.
this PR fixes that by updating the logic to only allow a plugin to override hooks/options set by their descendants (which was always the intent).
this is a breaking change, since it could mean that apps that work completely fine now might have silently ignored conflicts that this change would error on.

CPP-878 detect conflicts between cousin plugins

---

core/create/package.json
core/create/src/index.ts
package-lock.json

The tasks are not valid error was introduced in commit [463124a](https://github.com/Financial-Times/dotcom-tool-kit/commit/463124add8fd89dea013dfa892a5ebebf8b5537c), where version ranges caused toolkit core/create to import installHooks from .npm node_modules instead of the app level node_modules. This caused the Task function location to be `.npm/_npx/4fc902e927bad53b/node_modules/@dotcom-tool-kit/types/lib/index.js:9` and the rawPlugin tasks prototype location to be `empty_app/node_modules/@dotcom-tool-kit/types/lib/index.js:9` thus making `instantiatePlugin` fail at the `task.prototype instanceof Task` typecheck, throwing 'tasks are not valid'. We fix this by making sure we import installHooks at the app level's node_modules.

Fix tasks are not valid error

---

core/create/src/index.ts

- the current release version for core/create in main is [2.0.1](https://github.com/Financial-Times/dotcom-tool-kit/blob/main/core/create/package.json#L3), I want to bump it up to 2.0.2 
- the prerelease works 
https://user-images.githubusercontent.com/20088576/167165188-3da1d38c-59c0-4672-ba45-6e7f617c689d.mov

Bump create version

---

core/create/package.json
core/create/src/index.ts
core/create/src/logger.ts
package-lock.json

This error gets thrown when running `npm init @dotcom-tool-kit` and selecting both Eslint and Mocha, without being properly handled. This PR fixes this by dynamically importing hasToolKitConflicts to stop it from failing the instanceof check.
sidenote: before merging, will squash refactor into fix commit because I want to release the refactor commit as well after merging

Cpp-882 Fix 'There are problems with your Tool Kit configuration'

---

plugins/heroku/src/tasks/production.ts

When the staging app is promoted to production, the pipeline will enter a 'preboot phase' where both the old and new production apps are run in parallel and, once it is ready, requests will start being routed to the new app. This is to minimise downtime.
During the preboot phase, however, the formation cannot be changed, i.e., the app cannot be scaled to a different number of dynos. This process can take a few minutes so we can't just leave Tool Kit running waiting for it to make any scaling changes. Instead, let's scale the app before we promote the new version to production. This will mean that the old app might be scaled as well but I can't think of any reason this would be a concern.

CPP-843 Scale dynos before promoting them to production

---

lib/types/src/schema/node.ts
package-lock.json
plugins/node/src/tasks/node.ts

These could be either options for node like `--inspect` or arguments for the Node process you're starting. There's not a simpler way to do this seeing as there are no generalised configuration files applicable (unlike for `nodemon`.)

Allow arbitrary arguments to be set for node process in options

---

lib/types/src/schema/mocha.ts
package-lock.json
plugins/mocha/src/tasks/mocha.ts

We want to delegate as much configuration to tools themselves rather than exposing options via Tool Kit. Unfortunately, the mocha plugin was invoking mocha with a low-level API and skipping the code which reads configuration files, meaning that users could not set options like they can with plugins such as Jest and Webpack.
To solve this let's just invoke the mocha CLI directly rather than via a lower-level API so that it calls all the setup code it would for a normal invocation, including looking for configuration files. The user can also set the path for the config file explicitly in the Tool Kit options.
The files that mocha reads can now be set in its own configuration file so we don't really need to have them be set by Tool Kit. The option to do so might be removed in a future major …

CPP-898 Allow mocha to read config files

---

plugins/nodemon/src/tasks/nodemon.ts
plugins/nodemon/tsconfig.json

The `node` plugin writes the port it chooses to the `.toolkitstate` which the `next-router` plugin can then read from and register with the `next-router` server. nodemon was missing the same behaviour so let's copy it over.

Write chosen port for nodemon too

---

plugins/n-test/src/tasks/n-test.ts
plugins/pa11y/.toolkitrc.yml

We want to run `n-test` for both review and staging Heroku apps, so we should check for written state for both in the `n-test` plugin. Previously, `n-test` was failing if run on a deploy from the `main` branch, as deployments write to the `staging` state rather than `review` state during testing, but the plugin only read the `review` state.
We had also set up the Pa11y plugin to run test when staging but I don't think this is necessary – n-gage never does it. We can add support for it later if desired.

CPP-902 Check staging app name for staging tests

---

.circleci/config.yml

when merging to main, release-please workflow is triggered however there is no npm build step when merging to main so npx would pull the latest version instead of 13.17.0 specified in package-lock.json. 
Latest version - 13.19.3
logs:
✔  building graph order, existing package names: @dotcom-tool-kit/logger,@dotcom-tool-kit/n-test,@dotcom-tool-kit/pa11y
13.17.0 logs:
✔  building graph order, existing package names: @dotcom-tool-kit/n-test,@dotcom-tool-kit/pa11y

ci: pin release-please version to 13.17.0 as stated in package-lock.json

---

plugins/heroku/src/scaleDyno.ts

the appFormation array in scaleDyno.js try to check always the position 0 the type that it requested, but not always the type is in the position 0, so we have to be sure that it is in the position 0 always

Heroku plugin: filter appFormation array by type in scaleDyno.js

---

core/cli/CHANGELOG.md
core/create/CHANGELOG.md
lib/logger/src/helpers.ts
lib/types/src/index.ts

Due to https://github.com/googleapis/release-please/issues/1533, the changes in #245, aren't included in the generated release-please PR. I've made a few tweaks to the documentation in all the packages that were changed and appended the relevant commit headers in the footer of the messages, which release-please will interpret as new commit messages to include. This means that as well as calculating the version bumps correctly, the changes will also be listed in the CHANGELOG files and in the release notes.

Include commits from #245 in release-please release

---

lib/types/src/schema/pa11y.ts
package-lock.json
plugins/pa11y/package.json
plugins/pa11y/src/tasks/pa11y.ts

Instead of passing static options to Pa11y, calling the `pa11y-ci` binary instead reads config defined in a `.pa11yci[.js[on]]` file. Seeing as this can be a `.js` file, the config can be dynamically generated, making the tooling much more flexible. This was how n-gage interfaced with Pa11y.
This also solves an issue that reported validation errors from Pa11y as internal errors within Pa11y.

CPP-915 Allow Pa11y to use config defined in .pa11yci

---

plugins/pa11y/src/tasks/pa11y.ts

The fork function won't do any path resolution automatically, you need to do it first. This fixes a module resolution error.

Resolve path to pa11y-ci binary before forking it

---

package-lock.json
plugins/heroku/src/getPipelineCouplings.ts
plugins/heroku/src/tasks/production.ts

We want to scale apps before promoting them to production as the preboot phase after promotion can take minutes and scaling is not possible during that time. However, scaling will fail if this is the first time the app has been deployed, so do the deployment first then. Hopefully (!), there shouldn't be a preboot phase if we don't need to switch from an old version either so it should be safe to scale the app immediately afterwards.
I've been able to test and confirm that it runs the original code path for next-static (with `appIds.length` totalling `1`) but it would be much harder to confirm the other path is working seeing as we don't have any Heroku pipelines without deployed apps currently. Instead, I've left a log in the code to message the Platforms team if that path is reached.

CPP-942 Fix crash when trying to scale undeployed Heroku apps

---

package-lock.json
plugins/pa11y/jest.config.js
plugins/pa11y/package.json
plugins/pa11y/src/tasks/pa11y.ts
plugins/pa11y/test/pa11y.test.ts

Currently, in tool-kit’s pa11y plugin, we are running pa11y-ci directly, and there’s no code in the Pa11y Task to set the review app’s url. Looking at n-gage (that runs pa11y-ci directly as well), it exposes a [TEST_URL ](https://github.com/Financial-Times/n-gage/blob/9744dac1abfff71f931c0d71869c202801fa7a71/src/tasks/review-app.mk#L39) env var when generating the heroku review app, for pa11y config to use later. 
This PR sets TEST_URL environment variable to the review app's url in our pa11y task, which the .pa11yci relies on.

Cpp-949 set TEST_URL env var in pa11y task

---

orb/src/jobs/heroku-promote.yml

The change-api orb [defaults this parameter to "unknown"][1] which means that all our production deploys are associated with the "test" environment [in the Change API interface][2].
[Example job output of this behaviour is available][3].
[1]: https://github.com/Financial-Times/change-api-orb/blob/v0.25.1-patch/src/jobs/release-log.yml#L20
[2]: https://changes.in.ft.com/?productionOnly=true&systems=dotcom-debug-user
[3]: https://app.circleci.com/pipelines/github/Financial-Times/dotcom-debug-user/588/workflows/5f7e0034-d731-454c-98ee-b4e227538151/jobs/2201?invite=true#step-103-58

fix: pass environment to Change API

---

core/cli/src/plugin.ts
core/cli/src/rc-file.ts

We've found that it's quite easy to forget to create a `.toolkitrc.yml` config file for your custom plugin (even though it's mentioned in the documentation). Omitting the config file will mean that cosmiconfig will try and traverse parent directories until it finds a valid config. This will likely be the config at the app's root instead, which will (at least transitively) include the current plugin in its `plugin` property, causing an infinite loop of config resolution.
Let's try and catch when we've resolved the config to the same root version and print a warning to remind people this can have unexpected results. This probably won't catch loops when one plugin installs another within the `node_modules` directory, but at that point it's likely going to be a plugin we own and have audited …

CPP-937 Avoid infinite loops when custom plugins don't have a config file

---

lib/types/src/schema/prettier.ts
plugins/prettier/src/tasks/prettier.ts
plugins/prettier/test/tasks/prettier.test.ts

this (and the default value) are implemented in the Prettier CLI, not the API, so we should implement it in the task

fix: prettier plugin respects .prettierignore

---

core/create/src/index.ts

We've had an incident where an app didn't include the upload-assets-to-s3 plugin and its CSS and JS was unavailable in production. As this plugin is quite important (and used by most of our frontend apps) I think we should offer it during the init script.

feat: add optional upload-assets-to-s3 plugin when migrating

---

plugins/prettier/src/tasks/prettier.ts

Out of the box the prettier plugin should format the common file types used within customer products

Add jsx,json,tsx and ts file types to prettier defaults

---

package-lock.json

For some unknown reason, `import-from` was not being installed to a `node_modules` directory, even though it's a dependency of `import-cwd`, which is a dependency of the `@dotcom-tool-kit/create` package. This was affecting clones of this repository, breaking local runs of the `@dotcom-tool-kit/create` package. Just explicitly installing `import-from@3` into `create`, deleting the dependency from the `package.json`, then running `npm install` again seems to have unstuck the lockfile. :shrug:

Fix lockfile failing to install import-from package

---

.release-please-manifest.json
core/create/src/index.ts
package-lock.json
plugins/component/.toolkitrc.yml
plugins/component/index.js
plugins/component/package.json
plugins/component/tsconfig.json
release-please-config.json
tsconfig.json

Adding a component plugin that has the required Tool Kit plugins for our `n-*` components. Along with this, we have added a component option to the migration script so we can easily migrate our components to use Tool Kit.
Here is a video demo of this script working (with a small tweak to get it working locally):
[Screen sharing - 2022-11-09 7_23_05 PM.webm](https://user-images.githubusercontent.com/893208/201050818-d1bff232-47b7-4edb-8c54-07b7e0cb3058.webm)

CPP-979: Add component option to migration script

---

plugins/prettier/src/tasks/prettier.ts

`.json` was added to the default list of files to format by Prettier in https://github.com/Financial-Times/dotcom-tool-kit/pull/300, however this has added some unwanted complexity:
`package.json` and `package-lock.json` files are now being formatted which we don't want to happen, and `json` files are being indented with tabs which is not the usual pattern. There are options to override this config just for `json` files* but this adds more complexity and obfuscation inside Tool Kit.
This change therefore removes config for json altogether and then users can add it in their custom config file if they wish.
***options to override this config just for json files**
Updating the file list in the Prettier options to exclude package.json and package-lock.json will exclude them from being …

CPP-1028: fix(prettier): remove config for json files

---

plugins/circleci-heroku/src/index.ts

I think this was always an oversight rather than something we can only do now that we've made other improvements to the code.
The job now requires the `waiting-for-approval` job to have been run first, though this only runs for nori/renovate branches. If that job is filtered out then this job will instead simply run after `tool-kit/setup` is completed. n-gage would [previously](https://github.com/Financial-Times/next-user-facing-app-template/blob/bf8828c6fbdef6f7da706378c9dab9d5bef781c7/.circleci/config.yml#L189) create a different workflow for nori/renovate, with the `waiting-for-approval` job required before anything else was run. Tool Kit's approach is much simpler and reduces duplication.

CPP-751 Still run provision step for nori/renovate builds

---

core/sandbox/.toolkitrc.yml

On running `npx dotcom-tool-kit --install` in the sandbox the install fails because there are hook conflicts on run:local. This PR configures run:local in the sandbox .toolkit.rc file to get past this error.

fix(sandbox): resolve hook conflict

---

lib/logger/src/format.ts
lib/logger/src/helpers.ts

The Tool Kit logger prefixes each log message with labels to give context about where the message is coming from, e.g., which Tool Kit task or subprocess it's from. Some subprocesses (e.g., Jest) are prone to frequent stream flushing, causing their logs to be repeatedly interspersed with these labels greatly hindering readability. Let's work around this with a global variable that stores the last label we printed and only print another prefix if the label has changed, i.e., when the context for the message has changed.

CPP-1037 Reduce noise created by metadata prefixes

---

package-lock.json
plugins/circleci-heroku/src/index.ts
plugins/circleci/src/circleci-config.ts

Adding the `tool-kit/heroku-provision` job to the Nightly workflow. Our heroku apps would provision a review app as part of the Nightly scheduled workflow when the CircleCI config was not automated. We are adding the job back for our automated by Tool Kit configs.
This also includes a removing being able to set `filters` job options to Nightly workflow jobs. This is because we configure in CircleCI that our nightly workflows are triggered against the `main` branch only. Therefore if we add a job to be in the Nightly workflow, it shouldn't need to filter which branches it won't/will run against. And in the case for the `tool-kit/heroku-provision` job where it has a filter not to run against the `main` branch for our `tool-kit` workflow, we need to cancel this option for the `nightly` …

CPP-1027: add provision job to nightly workflow

---

package-lock.json
plugins/backend-app/.toolkitrc.yml
plugins/backend-app/package.json
plugins/component/.toolkitrc.yml
plugins/component/package.json

Add `@dotcom-tool-kit/secret-squirrel` as a dependency to our bootstrap plugins, `@dotcom-tool-kit/component` and `@dotcom-tool-kit/backend-app`. Adding the plugin as part of the migration (then into the template apps) should bring Tool Kit more align to feature parity to `n-gage`. We want `secret-squirrel` to be installed by default but, like n-gage, it is possible to remove it from an application.

CPP-1018: add secret squirrel to bootstrap plugins

---

plugins/upload-assets-to-s3/src/tasks/upload-assets-to-s3.ts

the upload-assets-to-s3 plugin works by looping over the files passed to it and uploading each to s3. When the files to upload includes a folder (with files inside) the directory itself is passed to s3 for upload.
s3 throws an error because it can only read files and not directories. This change updates the glob pattern of files to upload to not include directories.
The files within the directory are still uploaded successfully
**Before:**
list of files to upload includes `v2` which is a directory:
error is thrown (although files are still uploaded successfully):
**After:**
list of files to upload doesn't include any directories: 
files within the directory are still uploaded successfully:
top level:
inside `v2` directory:

fix(upload-assets-to-s3): only upload files

---

plugins/backend-app/readme.md
plugins/component/readme.md
plugins/frontend-app/readme.md

Add readmes for the bootstrap plugins; `backend-app`, `frontend-app`, and `component`.
https://financialtimes.atlassian.net/browse/CPP-876
https://financialtimes.atlassian.net/browse/CPP-877
https://financialtimes.atlassian.net/browse/CPP-1040

Add bootstrap plugin readmes

---

plugins/circleci-heroku/readme.md
plugins/circleci-npm/readme.md
plugins/circleci/readme.md
plugins/heroku/readme.md
plugins/husky-npm/README.md
plugins/npm/readme.md
plugins/prettier/readme.md
plugins/secret-squirrel/readme.md

A quick tidy up on the readme's we've done so far (each point has its own commit):
- standardise title
- add paragraph to those that are installed as part of the bootstrap plugins
- added some missing content

Readme tidy up

---

.circleci/config.yml
package-lock.json
package.json

We are jumping from v13 to v15. [v14](https://github.com/googleapis/release-please/releases/tag/v14.0.0) was breaking because it dropped support for Node 12, which we don't use, and [v15](https://github.com/googleapis/release-please/releases/tag/v15.0.0), which just released yesterday, and doesn't seem to make any breaking changes that would affect us.
We previously had an [issue](https://financialtimes.atlassian.net/browse/CPP-908) where newer versions of release-please would be incorrectly trying to create releases for packages that didn't need updating. I tested to see whether this applied to v15 too and couldn't reproduce the issue, though we currently already have 29 updates due.

CPP-910 Bump release-please to v15

---

docs/faq.md

add more clarity on installing a plugin in the case where Tool Kit has already been set up in a project.
The card reads:
Add documentation that explains how to add a plugin (that isn’t setup by the migration) to an existing tool kit project
This document should explain:
- how the configuration has been chosen
- how the plugin installs a hook
- how to select a hook for the plugin’s task to run in
- include using npx dotcom-tool-kit --help to review what has been done
However, I actually think most of that is well explained in the README's for the individual plugins, so I think maybe something on the top level README that introduces installing individual plugins might do.

CPP-1012: docs: add more clarity on installing a plugin

---

release-please-config.json

These changes should improve the behaviour of release-please so that
1. new components are not incorrectly assigned a tag of `v2.0.0` when initially released
2. changelogs only include changes relevant to each component, an issue we were seeing since we [updated](https://github.com/Financial-Times/dotcom-tool-kit/pull/329) to release-please `v15.0.0`.
Further details can be found in the commit descriptions. I have tested the behaviour by running release-please locally.

Fix issues with release-please configuration

---

plugins/typescript/.toolkitrc.yml

This was erroring for me because the casing was incorrect. This should address the issue and stop me having to manually override.

fix: correct TypeScript casing

---

plugins/lint-staged-npm/readme.md
plugins/lint-staged-npm/src/index.ts
plugins/lint-staged/readme.md

Add the READMEs for the `lint-staged` and `lint-staged-npm` plugins.

CPP-866 CPP-867 Add lint-staged READMEs

---

orb/src/@orb.yml
orb/src/jobs/heroku-promote.yml
orb/src/jobs/setup.yml

The Edge Delivery & Observability team updated the change-api orb to be a bit more streamlined and [released a new major version](https://github.com/Financial-Times/change-api-orb/releases/tag/v1.0.0). The main interesting change for us the removal of the dependency on `jq`, which means we don't have to run a command in our `tool-kit/setup` job to install `jq`, which was redundant if you weren't calling the Change API in a given workflow. Updating to the latest version also means we can get future feature releases automatically.

CPP-1022 Update Tool Kit orb to use change-api's 1.0 orb release

---

docs/faq.md
readme.md

There have been support requests that suggest that people may think that Tool Kit is setup to handle all scripts and packages. This PR is to update the intro to the Tool Kit readme to highlight that Tool Kit is to enable packages in the FT.com workflow and not to control all aspects of the package.

CPP-1017: Readme intro update

---

plugins/mocha/readme.md

Some projects in Customer Products make use of code coverage reports to check that their unit tests are sufficiently thorough. I've add some documentation on how to get code coverage working with mocha, which requires the [nyc](https://github.com/istanbuljs/nyc) tool.
Seeing as Jest has [built-in support](https://jestjs.io/docs/configuration#collectcoverage-boolean) for code coverage reports I didn't add documentation in its own plugin as it felt redundant when users could just refer to Jest's own docs/configuration.

CPP-1026 Document how to integrate code coverage reports with mocha

---

lib/types/src/schema/upload-assets-to-s3.ts
package-lock.json
plugins/upload-assets-to-s3/README.md
plugins/upload-assets-to-s3/package.json
plugins/upload-assets-to-s3/src/aws.d.ts
plugins/upload-assets-to-s3/src/tasks/upload-assets-to-s3.ts
plugins/upload-assets-to-s3/test/tasks/upload-assets-to-s3.test.ts
tsconfig.settings.json

This PR improves some aspects of the `UploadAssetsToS3` task. Each change is captured in a commit. The final change is the one that I'd like consideration on:
Currently if no files match the provided directory and glob the code continues to run and no logging indicates to the user that files haven't been found and uploaded. This change throws an error if no files are found that match the provided glob.
Update documentation and default options to reflect the following points:
- My understanding is that support for multiple production buckets in this task is for the case where there exists a `prod` and `prod-us` bucket. However, the common use case (I haven't yet found a conflicting example) in Customer Products for the projects where there is a `prod` and `prod-us` S3 bucket is that the …

CPP-1070 Uploadassetstos3 improvements

---

lib/types/src/schema/serverless.ts
package-lock.json
plugins/serverless/package.json
plugins/serverless/readme.md
plugins/serverless/src/index.ts
plugins/serverless/src/tasks/run.ts
plugins/serverless/tsconfig.json
tsconfig.json

Create a serverless plugin for managing Lambdas. This PR creates the initial plugin structure as well as a `ServerlessRun` task for use on the `run:local` hook.
The `ServerlessRun` task uses the `serverless offline start` command which mirrors how most CP lambdas are run locally. See [the Supporting AWS lambdas in Tool Kit](https://financialtimes.atlassian.net/wiki/spaces/CPP/pages/7966326832/Supporting+AWS+lambdas+in+Tool+Kit ) confluence page for the initial discovery around how this plugin would be implemented to best work with existing CP Lambda practices.

CPP:1051 - feat: add serverless plugin

---

plugins/circleci-deploy/tsconfig.json
plugins/cypress/tsconfig.json
plugins/lint-staged/tsconfig.json
plugins/mocha/tsconfig.json
plugins/node/tsconfig.json
plugins/pa11y/tsconfig.json
plugins/secret-squirrel/tsconfig.json
plugins/webpack/tsconfig.json

We noticed in a previous PR that the references in the `tsconfig` files in some plugins were out of date. This tides them up.

fix: tidy up references in tsconfig files

---

plugins/heroku/src/declarations.d.ts
plugins/heroku/src/tasks/production.ts
plugins/heroku/test/tasks/production.test.ts

We need different deployment behaviour for Heroku apps depending on whether they've been deployed before or not. Previously, we'd just check for whether an app existed in the pipeline, but this isn't a useful heuristic as apps are apparently created before a build is run. So let's instead call the Heroku API and see what the `slugSize` of an app is: this value appears to be `null` until the app has been build and promoted to production.
This does mean that we're making an extra API call before we deploy an app, but this should hopefully result in more reliable deployments.

Properly test if app has been deployed previously

---

plugins/babel/src/run-babel.ts

This PR fixes an issue for the Babel plugin identified when using it to transpile code in a Serverless app: https://github.com/Financial-Times/cp-metrics-catcher.
The file directory for the app is:
```
.
└── src
├── clients
│	└── cloudwatch.js
└── functions
└── heroku-token-rate-limit
├── index.js
└── lib
└── get-remaining-requests.js
```
Running `dotcom-tool-kit build:local` with `'@dotcom-tool-kit/babel` set as a plugin in `.toolkitrc.yml` currently errors with:
```
ENOENT: no such file or directory, open 'lib/clients/cloudwatch.js'
```
This is because the root directory of the output path (which defaults to `lib`) is created via the below line of code, which only creates the `lib` directories (and no sub-directories as it does not yet have knowledge of any).
```js
await …
```

fix(babel): making destination folders for transpiled code

---

lib/types/src/circleci.ts
lib/types/src/schema.ts
lib/types/src/schema/serverless.ts
orb/src/@orb.yml
orb/src/commands/serverless-assume-role.yml
orb/src/jobs/heroku-provision.yml
package-lock.json
package.json
plugins/circleci-deploy/package.json
plugins/circleci-deploy/src/index.ts
plugins/serverless/readme.md
plugins/serverless/src/index.ts
plugins/serverless/src/tasks/provision.ts

This adds a task to the serverless plugin to deploy review apps to AWS via Serverless. The task itself tries to mirror the `provision` target present in the `Makefile`'s of projects still using n-gage to deploy to AWS, like [next-anubis-config-api](https://github.com/Financial-Times/next-anubis-config-api/blob/39f48d9d100d5d3d8fceeec0459e19d77e1f1a9d/Makefile#L24). The main point of interest is the introduction of using [OIDC tokens](https://tech.in.ft.com/tech-topics/continuous-delivery/circleci-aws-oidc-authentication#create-circleci-config-using-the-aws-cli-orb-in-your-project) to [deploy to CircleCI](https://circleci.com/docs/openid-connect-tokens/). I've had to add some additional logic to the plugin loading code and the Tool Kit orb in order to support this, as it requires the use …

CPP-1053 Add ServerlessProvision task with OIDC token support

---

plugins/next-router/readme.md

This PR updates the `next-router` plugin's README to clarify the value required for the `appName` option for the `next-router` plugin.

docs: next-router plugin README updates

---

core/cli/src/config.ts
core/cli/test/files/conflict-resolution/.toolkitrc.yml
core/cli/test/files/duplicate/.toolkitrc.yml

Now that we've moved the setting of default options into the zod schema validation, we need to make sure we're using zod to parse options for plugins even when no options have been specified explicitly in your `.toolkitrc.yml` config. This is also important to ensure that plugins with required options are having those set.
For example, @andygout was encountering an [issue](https://financialtimes.slack.com/archives/C3TJ6KXEU/p1678702462886019) with the latest Tool Kit versions where the `run:local` hook was failing to run with an error
```
Nodemon:
Cannot destructure property ‘entry’ of ‘this.options’ as it is undefined.
```
This is because `nodemon` has a default value [specified](https://github.com/Financial-Times/dotcom-tool-kit/blob/5a450eabee673c8a4ceecf72f6eba7bf2e9dfcd2/lib/types/src …

Validate options even when none are given for a plugin 

---

lib/types/src/schema/eslint.ts
lib/types/src/schema/prettier.ts

Originally, these files options just accepted strings, but they were modified to accept arrays of strings too whilst we were adding lint-staged support so that that plugin could pass in an array of globs. We allowed single strings to still be set as options in order to preserve backwards compatibility, but when writing the original schemas for the migration script the option was encoded as a string array because we planned to deprecate a single string option eventually so it made sense for the migration script to only offer new users to create a list of file globs. However, this became a problem when we translated that schema into a zod schema that would also be used to validate the options a user has set, as that original schema did not allow single strings. This inadvertently created a …

Allow prettier/eslint files options to be simple strings as well as arrays

---

package-lock.json
plugins/frontend-app/.toolkitrc.yml
plugins/frontend-app/package.json

We include webpack in the frontend-app bootstrap plugin to compile frontend assets. We should include upload-assets-to-s3 so those assets are deloyed in production to the asset s3 bucket.

CPP-1353: add upload-assets-to-s3 plugin to frontend app

---

core/cli/src/messages.ts
core/create/src/index.ts
core/create/src/logger.ts
core/create/src/prompts/conflicts.ts
core/create/src/prompts/options.ts

As part of #368, I knew I'd have to add support for zod's union types to the `create` package so that it could handle unions of types when prompting the user to enter options as part of a migration (it now does this by prompting for the first type in the list of union types). However, when I was testing this change I found that the create script would fail when creating a new Tool Kit config using a standard preset like `backend-heroku-app`. It would throw errors about the `heroku` and `vault` plugins having missing options (or in fact it would just say there were problems with the installation – I've added logging for the `ToolKitError` in this PR too). This is because we do an install of Tool Kit before we prompt the user for any options to set so that we can get the configuration it …

Fix zod validation issues with the create package

---

lib/types/src/schema/vault.ts

In theory, these fields should be required as Vault won't work without them, but not every app that pulls in the Vault plugin actually needs to use Vault, e.g., an app that uses the `nodemon` plugin with the `useVault` option set to false. In the future we could investigate alternative approach which could conditionally require the options in some circumstances but I'm not sure how that would look.
This was inspired by but does not fix https://github.com/Financial-Times/cp-content-pipeline/pull/328. Other plugins, like `@dotcom-tool-kit/heroku` also have required options, but don't have any options that would mean they should be ignored in certain circumstances.

Make vault options optional

---

core/create/src/index.ts

This was causing a crash as `dotcom-tool-kit` is only a dev dependency of the `create` package. Rather than promoting it to a full dependency to use `loadConfig`, I remembered that [in other places in the package](https://github.com/Financial-Times/dotcom-tool-kit/blob/453ebf57ecbfaff8266f6dffbea1523247fb4aaf/core/create/src/prompts/conflicts.ts#L31-L33) we use the version of `dotcom-tool-kit` that we install into the user's own project as part of the migration to avoid `instanceof` incompatibilities. It makes sense to keep doing the same thing here to avoid accidentally bumping into further incompatibilities in future code changes.

Load Tool Kit configuration via a user's local dotcom-tool-kit package

---

plugins/circleci/src/circleci-config.ts

Quick PR as I noticed when experimenting with `cp-content-pipeline` that since the revamp to the CircleCI plugin, the installation error for CircleCI configurations that are unmanaged by Tool Kit (i.e., they don't have the generated comment at the top of the file) get an unhelpful error when the configuration is missing expected code, e.g.,
```
could not automatically install hooks:
───────────────────────────────────────────────────────────────────────────
- Please update your CircleCI config to include the 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 job(s) in the tool-kit workflow and the 0, 1, 2, 3, 4 job(s) in the nightly workflow
```
This was because we were getting the keys of arrays which are, of course, numbers in JavaScript lol. There's only so much TypeScript can help us! This now …

Fix installation error for unmanaged CircleCI configs

---

plugins/mocha/src/tasks/mocha.ts

As with many CLI tools, mocha supports ANSI colours for its test reporting but disables them if it's not connected to a TTY (i.e., if it's not an interactive session, such as when it's run in a CI or if it's being piped to another script). It doesn't detect a TTY in our case as we're piping its stdout and stderr through our winston logging infrastructure rather than outputting to the user's terminal directly. In order to get colourful output then, let's force it via mocha's [`--color`](https://mochajs.org/#-color-c-colors) option.

Force color output for mocha logs

---

package-lock.json
plugins/n-test/package.json

see https://github.com/Financial-Times/dotcom-tool-kit/pull/381. This is required to unblock failing builds on next-article.
This is not a breaking change

chore: bump to latest version of n-test to get versions back aligned

---

package-lock.json
plugins/serverless/package.json

Ran `cd plugins/serverless && npm install @dotcom-tool-kit/types@latest` to fix the build error for the latest changes in #372.

fix(serverless): update @dotcom-tool-kit/types

---

core/create/src/index.ts
core/create/src/prompts/conflicts.ts

We need to do this otherwise `cosmiconfig` will return us the old, cached options when we want to do our first install. This has only been causing us obvious issues since the migration to zod because the validation complains about the options that weren't defined when originally loading the config, but it would likely have caused subtle bugs in the installation process previously too.

Clear config cache for migration script after updating options

---

core/create/src/prompts/main.ts
orb/src/jobs/deploy-production.yml
package-lock.json
plugins/backend-serverless-app/.toolkitrc.yml
plugins/backend-serverless-app/index.js
plugins/backend-serverless-app/package.json
plugins/backend-serverless-app/readme.md
plugins/circleci-deploy/package.json
plugins/circleci-deploy/src/index.ts
plugins/serverless/src/index.ts
release-please-config.json

This PR adds a new Tool Kit plugin that users can include to bundle the baseline recommended configuration for a Serverless project.

CPP-1057 Add a serverless preset plugin

---

orb/src/jobs/deploy-production.yml
orb/src/jobs/heroku-promote.yml

Since using change-api@1.0.1, it no longer evaluates our system-code parameter as the value of the environment variable $CIRCLE_PROJECT_REPONAME. Instead it sends the string "CIRCLE_PROJECT_REPONAME" which fails the call to the change api (see slack thread linked below). According to the CircleCI docs (linked below), there is a parameter type of `env_var_name` which you provide a string of the environment variable name. This should pass the value of the $CIRCLE_PROJECT_REPONAME to the change-api call.
Relevant slack thread:
https://financialtimes.slack.com/archives/C02HH3JAQ5V/p1681485994978449?thread_ts=1681483126.496729&cid=C02HH3JAQ5V
CircleCI doc:
https://circleci.com/docs/reusing-config/#environment-variable-name

CPP-1372: Use env_var_name type for defining system-code for change-api orb

---

.circleci/config.yml

[Code Management have created us a CircleCI context](https://financialtimes.slack.com/archives/C02ST9MNV0S/p1681727613774559?thread_ts=1681725871.981079&cid=C02ST9MNV0S) that contains a `CIRCLE_TOKEN` that has permanent permissions to publish our dotcom-tool-kit Orb. This PR implements this new context. I have also made a copy of the old `CIRCLE_TOKEN` in vault called `CIRCLE_TOKEN_COPY` and deleted the original. If this works as expected, I will delete the copy.

CPP-1372: use circleci context to deploy orb

---

.circleci/config.yml
core/cli/package.json
core/create/package.json
lib/wait-for-ok/package.json
package-lock.json
package.json

Drops support for Node 14. This doesn't involve any changes to the code, but it marks the end of our support for Node 14 and potentially the beginning of us writing code that is not compatible with the older runtime.

Drop support for Node 14

---

orb/src/@orb.yml
orb/src/jobs/deploy-production.yml
orb/src/jobs/heroku-promote.yml

Reverts Financial-Times/dotcom-tool-kit#402 and update to new Change API Orb which fixes the change-log job.

Revert #402 and update change-api-orb

---

plugins/circleci/src/circleci-config.ts

After dropping support for Node 14 in this repo (#409), our orb was also bumped to a new major version. This PR updates the CircleCI plugin to use the new major orb version.

fix(circleci): update majorOrbVersion to new published major version

---

package-lock.json
package.json
tsconfig.settings.json

This sets the `target` and `library` compiler options so that we aren't polyfilling any ECMAScript constructs that Node 16 supports natively, and the latest Node 16 library functions are type checked properly. It will be easier to remember to update this base configuration once we move to Node 18 than updating the options directly. These base options are defined [here](https://github.com/tsconfig/bases/blob/821d9aa0b2e075949b6764c1e4556f83ab7554a9/bases/node16.json).
It also sets some useful recommended default options, including some that we were already using which I've now removed as they're redundant.

CPP-1248 Use standard tsconfig base for Node 16

---

.circleci/config.yml
package.json

This PR does the necessary groundwork to start running and testing Tool Kit with Node 18. The pinned Volta version is Node 18 (and the `npm@9` version that is bundled with it), updating the `engines` field to officially support it, and running CI builds against it. **This does not mean that we now support updating projects that use Tool Kit to Node 18**. Instead, this is just the first step in ensuring we can support that by making sure the code is compatible with the new runtime version.

CPP-1335 CPP-1336 Support running Tool Kit with Node 18 (NOT supporting using Node 18 in Tool Kit projects)

---

lib/types/src/schema/node.ts
lib/types/src/schema/nodemon.ts
plugins/node/readme.md
plugins/node/src/tasks/node.ts
plugins/nodemon/readme.md
plugins/nodemon/src/tasks/nodemon.ts

We aren't ready to support native `fetch` yet as we're still using `node-fetch`/`isomorphic-fetch` in a lot of places and there will likely be subtle bugs we'll have to hunt for as part of a concentrated migration. In the meantime, to facilitate the migration to Node 18, Tool Kit will run its forked Node processes (i.e., `npm start`'ing Customer Products apps) with the `--no-experimental-fetch` flag set so that we can make the most of Node 18 whilst excluding the native `fetch` implementation. Passing this flag to a Node runtime that doesn't know about native `fetch` will result in the error
```
bad option: --no-experimental-fetch
```
so we need to use the builtin [`process.allowedNodeEnvironmentFlags`](https://nodejs.org/dist/latest-v18.x/docs/api/process.html#processallowednodeenvironmen …

CPP-1337 Disable native fetch in forked Node processes

---

lib/types/src/npm.ts

The terminating anchor was seemingly removed accidentally in a [previous commit](https://github.com/Financial-Times/dotcom-tool-kit/commit/72d2faa644b8c0e1c71131e3559e802017f0d0f5), but it's necessary to make sure prerelease versions don't use the `latest` tag on npm. e.g., `1.0.0-beta.1` would match the previous regex as the `1.0.0` substring would match, however it wouldn't match the new regex as the string continues afterwards, so the `$` does not match.

Make npm regex for determining release tags stricter

---

orb/README.md
orb/src/executors/default.yml
plugins/circleci/src/circleci-config.ts

CPP-1338 Bump default docker executor versions to Node 18

---

plugins/next-router/src/tasks/next-router.ts

next-router uses `isomorphic-fetch` which will be overridden by native `fetch` and cause weird behaviour so let's disable native `fetch` until we've cleaned next-router up. I don't _think_ any other plugins that `fork` Node processes will be affected by this – the next-router plugin is the only one dependent on `isomorphic-fetch` and other plugins are for much bigger packages which need to connect to the internet far less.

Disable native fetch in forked next-router processes as well

---

orb/src/@orb.yml

The latest change-api orb drops the use of `--retry-all-errors` and `--fail-with-body`. These were new curl options which wasn't available for the CircleCI containers we use.

CPP-1372: use latest change-api-orb to fix change-api curl request

---

orb/src/executors/default.yml
plugins/circleci/src/circleci-config.ts

As part of adding support for Node 18 to Tool Kit we [bumped](https://github.com/Financial-Times/dotcom-tool-kit/pull/419) the default Node version used for CircleCI configurations so that they would be Node 18 if they weren't overridden by the `circleci` plugin's `nodeVersion` option. So currently any Tool Kit task will fail if you haven't overridden `nodeVersion` and you aren't using Node 18 in your CircleCI config, pushing you to run `dotcom-tool-kit --install` to update the config. However, we haven’t finished testing all our libraries to make sure Node 18 is fully supported yet, so we shouldn't be pushing people to Node 18 prematurely.

Revert default CircleCI executor back to Node 16

---

package-lock.json
plugins/heroku/src/buildHerokuReviewApp.ts
plugins/heroku/src/checkIfStagingUpdated.ts
plugins/heroku/src/createBuild.ts
plugins/heroku/src/declarations.d.ts
plugins/heroku/src/getHerokuReviewApp.ts
plugins/heroku/src/getHerokuStagingApp.ts
plugins/heroku/src/getPipelineCouplings.ts
plugins/heroku/src/gtg.ts
plugins/heroku/src/herokuClient.ts
plugins/heroku/src/promoteStagingToProduction.ts
plugins/heroku/src/repeatedCheckForBuildSuccess.ts
plugins/heroku/src/repeatedCheckForSuccessStatus.ts
plugins/heroku/src/scaleDyno.ts
plugins/heroku/src/setConfigVars.ts
plugins/heroku/src/setStagingSlug.ts
plugins/heroku/src/tasks/production.ts
plugins/heroku/src/tasks/review.ts
plugins/heroku/src/tasks/staging.ts
plugins/heroku/test/createBuild.test.ts
plugins/heroku/test/getHerokuReviewApp.test.ts
plugins/heroku/test/getHerokuStagingApp.test.ts
plugins/heroku/test/getPipelineCouplings.test.ts
plugins/heroku/test/gtg.test.ts
plugins/heroku/test/repeatedCheckForBuildSuccess.test.ts
plugins/heroku/test/repeatedCheckForSuccessStatus.test.ts
plugins/heroku/test/scaleDyno.test.ts
plugins/heroku/test/setConfigVars.test.ts
plugins/heroku/test/setStagingSlug.test.ts
plugins/heroku/test/tasks/review.test.ts

We've long had a problem where errors thrown when getting a unsuccessful status code from the Heroku API neither include the actual error response body from Heroku, nor provide any information on what API call was the one that caused the error. The `heroku-client` package itself is largely to blame for this: it does bundle up a good amount of information in the errors it throws, but it's hidden away in added fields to the `Error` class that the client doesn't document anywhere.
For this PR, I've augmented the errors thrown from the Heroku API to include the response body from the API, as well as requiring code to pass an argument describing what it's going to use the Heroku client for before you can use the client managed by `herokuClient.ts`. This means we can always provide additional …

CPP-1285 Improve Heroku errors

---

plugins/circleci/readme.md

as it's not obvious that this should be a docker image tag rather than a semver node version

docs: clarify what nodeVersion option is used for in circleci plugin

---

package-lock.json
plugins/n-test/package.json

there is a beta version of n-test which supports node.js 18 so let's use that in the node.js 18 supporting version of the n-test plugin

feat: use latest version of n-test

---

lib/types/src/schema/circleci.ts
plugins/circleci-deploy/src/index.ts
plugins/circleci-npm/src/index.ts
plugins/circleci/readme.md
plugins/circleci/src/circleci-config.ts
plugins/circleci/src/index.ts
plugins/circleci/test/circleci-config.test.ts

This PR adds the ability to run CI code with multiple versions of Node using CircleCI's [matrix jobs](https://circleci.com/docs/using-matrix-jobs/). This is useful when your project supports multiple different Node versions and you want to test that your code is compatible with all of them. To use the matrices you specify an array of Node versions for `@dotcom-tool-kit/circleci`'s `nodeVersion` option and the plugin will install a CircleCI executor for each and split each job that supports running multiple times (i.e., test and build jobs, but not deploy jobs). In order to maintain simplicity in the plugin (which benefits maintainers of both the Tool Kit repository and custom plugin authors), any job that supports matrices will always be passed a list of Node versions to run, even if the …

CPP-1320 Support Node version matrices in CircleCI plugin

---

plugins/circleci/src/circleci-config.ts
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/test/files/with-hook/.circleci/config.yml

This avoids the [same issue we see in n-gage projects](https://github.com/Financial-Times/n-tracking/pull/119) where depending on all the Node version matrix jobs when 'fanning-in' with a job that does not use a matrix meant that we could not attach the workspace as the `node_modules` directory in the matrix jobs conflicted. The downside now is that the fanned-in job will still run even if a matrix job for an older Node version fails. I don't think CircleCI provides any way to work around this when testing multiple Node versions concurrently (there's no way to select which job to attach a workspace from, for instance).

Don't depend on all Node versions for joining jobs in CircleCI configurations

---

plugins/circleci/src/circleci-config.ts

An extra boilerplate object was left to be spread in nightly CircleCI jobs after #432. This object set the `executor` of a job to `node` – a docker image using the default Node version for the package – but this was redundant as the `jobBase` object on the line above already specified the `executor`, either as `node` or a matrix of different possible executors, e.g.,
```yaml
- tool-kit/build:
name: tool-kit/build-<< matrix.executor >>
requires:
- tool-kit/setup-<< matrix.executor >>
matrix:
parameters:
executor:
- node
- node16_20
executor: node
```
I don't think this previously generated CircleCI configuration was broken, but the extra `executor` field is unnecessary and (hopefully) overridden by the matrix parameters. I've tested these changes with n-express and don't think there should …

Don't include executor setting twice for nightly jobs in generated CircleCI config

---

readme.md

The CircleCI status badge has stopped loading; I'm not sure when it stopped loading. We were previously using a URL with an API token in so that the status would show when Tool Kit was a private repository, and we should probably have removed that token sooner once it was public lol? Doesn't matter now as the token is long expired (I've confirmed via the CircleCI API) I've regenerated the badge using the CircleCI UI.

Fix CircleCI status badge

---

plugins/circleci/src/circleci-config.ts
plugins/circleci/test/__snapshots__/circleci-config.test.ts.snap
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/test/files/with-hook/.circleci/config.yml

This keeps the code consistent across jobs that do and do not use Node matrices. The `waiting-for-approval` job cannot take Node versions as a matrix as it is not a job defined in the `dotcom-tool-kit` orb, so we don't append the executor to its name either. This should happen in jobs that don't use multiple executors too so we don't get CircleCI errors about referring to a `waiting-for-approval-node` job that has never been defined.
I thought I'd caught all the bugs introduced by #432 in #439 after testing with the `n-express` project. However, this issue is only found in repositories that use a job that shouldn't be split into a matrix but also needs to wait for approval, i.e., the `deploy-review` job used for Heroku review deployments, so I only encountered it after testing a Heroku …

Fix CircleCI configuration error by never appending executor name to approval job

---

core/cli/readme.md
core/cli/src/index.ts
core/cli/src/plugin.ts
lib/types/src/schema.ts
lib/types/src/schema/dotcom-tool-kit.ts
lib/types/src/schema/node.ts
lib/types/src/schema/nodemon.ts
plugins/next-router/src/tasks/next-router.ts
plugins/node/readme.md
plugins/node/src/tasks/node.ts
plugins/nodemon/readme.md
plugins/nodemon/src/tasks/nodemon.ts

We don't yet want to support Node 18's new fetch implementation. Tool Kit is enabling this by passing the `--no-experimental-fetch` flag to processes forked by the Node and Nodemon tasks. However, plenty of other tasks (e.g., Jest and Mocha) also involve spawning child Node processes and they don't have this flag passed to them. This can cause issues when running tests, for example.
Instead of adding a code snippet to each relevant task to make sure fetch is disabled, let's handle the flag at the top-level by setting it in the global `process.execArgv` object that will be read by all calls to `fork()`.
This presents the issue of how we're going to let users opt out of the behaviour if they legitimately want to use the new fetch. Previously, users would have to set an option for each …

Disable Node 18's native fetch across all plugins

---

lib/logger/src/format.ts
lib/logger/src/helpers.ts
lib/logger/src/index.ts
lib/logger/src/logger.ts
lib/logger/src/transports.ts
plugins/nodemon/src/tasks/nodemon.ts

Intercepting subprocesses' logging is a hairy proposition but it's necessary in Tool Kit to be able to add additional context for which thing that we've invoked is logging what. @AniaMakes recently reported some issues she was having with the logger in her project which should be fixed now. I also stumbled on another issue whilst testing the fix for the first. Technical details are in the commit descriptions but I'll include some before/after screenshots here to demonstrate the impact of the fixes.
vs
vs

CPP-1516 Improve the logger's robustness

---

plugins/circleci-heroku/package.json

This change should have been part of the [commit](https://github.com/Financial-Times/dotcom-tool-kit/commit/331ae1a11a17da0baa7db4e0c15a10a8420b6fb8) to use the `circleci-deploy` and `heroku` plugins and moving any code out of this package, replacing it with a shim `index.js` file. The `main` field now points to `index.js`, meaning that `require`'ing the package no longer returns an error about `lib/index.js` not existing.
Also include all files in the npm package now that we aren't generating any build artefacts.
Fixes the issue seen in https://github.com/Financial-Times/platform-scripts/pull/29.

Fix installation errors with circleci-heroku

---

plugins/jest/package.json

release notes:
- https://jestjs.io/docs/28.x/upgrading-to-jest28
- https://jestjs.io/docs/upgrading-to-jest29
all the changes are in Jest itself, not the CLI, which means this is safe to release as a minor version. existing users of the Jest plugin will still use the version they have in `package-lock.json`. new users will i believe get v29 automatically installed. that's probably fine.

feat(jest): support jest v28 and v29

---

package-lock.json
plugins/cypress/package.json
plugins/cypress/src/tasks/cypress.ts

`next-appetite` currently [extends the CypressLocal task ](https://github.com/Financial-Times/next-appetite/blob/main/toolkit/cypress/index.js)to pull in vault environment variables.
We want to do similar for `cp-content-pipeline` therefore we should have this logic in tool-kit.

feat(cypress): pull vault env variables into local hook

---

lib/doppler/src/index.ts

We aren't ready for people to move to Doppler yet so let's comment out the logger message encouraging them to do so for now.

Don't print Vault migration warning message just yet

---

plugins/serverless/src/tasks/deploy.ts
plugins/serverless/src/tasks/provision.ts

CI failed to provision a review app as the it could not find the serverless command which would be in the $PATH.
https://app.circleci.com/pipelines/github/Financial-Times/next-url-management-api/1710/workflows/f401f0d4-88bf-4c89-a71e-e91b21019b63/jobs/7209?invite=true#step-106-1081_30

CPP-1695: recover $PATH env

---

plugins/heroku/src/declarations.d.ts
plugins/heroku/src/gtg.ts
plugins/heroku/src/promoteStagingToProduction.ts
plugins/heroku/src/tasks/staging.ts
plugins/heroku/test/gtg.test.ts
plugins/heroku/test/promoteStagingToProduction.test.ts
plugins/heroku/test/tasks/staging.test.ts

Heroku made a [change](https://devcenter.heroku.com/changelog-items/2597) to the naming of the domain apps run on a couple of months ago. Previously, the domain would be based on the name of the app, but now a random 12-character string is appended to make them more unique I guess. This change only affects newly created apps.
We were assuming the previous format when constructing the URL for gtg tests. This meant that gtg tests have started to fail when deploying new apps. The correct domain is actually returned by the [same API](https://devcenter.heroku.com/articles/platform-api-reference#app-info) that we were previously using to check app names/convert to names from an app ID, so let's use that. This works for apps using the old domain naming system as well as the new one.
Tested on …

CPP-1509 Support new Heroku apps which now include random identifier

---

lib/doppler/src/index.ts
plugins/heroku/src/setConfigVars.ts
plugins/heroku/test/setConfigVars.test.ts

We plan to use the Doppler's official [Heroku integration](https://docs.doppler.com/docs/heroku) so we don't need to upload secrets from Doppler to Heroku here. Also note that the generated config vars (`REGION`, `NODE_ENV`, and `SYSTEM_CODE`) will now be stored in Doppler in [branch configs](https://docs.doppler.com/docs/branch-configs) instead to maintain a single source of truth (and also because it will override any we set ourselves here.)

Skip syncing Doppler secrets to Heroku in favour of official integration

---

plugins/n-test/src/tasks/n-test.ts

Workaround n-test [naïvely appending](https://github.com/Financial-Times/n-test/blob/2da4f1a20e11269475d3d65c7671e319bd256bcf/lib/smoke/setup-page.js#L46C31-L46C31) paths to a base URL meaning the host option cannot end in a trailing slash (as it will result in n-test incorrectly testing URLs like `https://example.com//` instead). I'd prefer to fix the logic in n-test to append the path to the host correctly using `new URL(path, host)` [to treat the `host` as a base URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#syntax), but unfortunately a few [repositories](https://github.com/Financial-Times/next-errors/blob/294fb605afb9e83de3de6e3071f4525e3f816bc7/Makefile#L8) include a path prefix in their host option and this change would break their tests. So let's hack around the …

Strip trailing slashes in host URL passed to n-test

---

lib/vault/package.json
package-lock.json
plugins/next-router/package.json

This removes n-logger across Tool Kit's non-development dependencies. This means that apps which use Tool Kit will no longer install n-logger as a development dependency.

Remove n logger

---

core/create/src/prompts/oidc.ts
lib/doppler/src/index.ts
plugins/heroku/src/promoteStagingToProduction.ts
plugins/heroku/src/tasks/review.ts
plugins/heroku/src/tasks/staging.ts
plugins/heroku/test/promoteStagingToProduction.test.ts
plugins/heroku/test/setConfigVars.test.ts
plugins/heroku/test/tasks/review.test.ts
plugins/heroku/test/tasks/staging.test.ts
plugins/serverless/src/tasks/deploy.ts

Follow up to https://financialtimes.slack.com/archives/C04B0SADVNJ/p1696258930072679 and https://github.com/Financial-Times/platform-scripts/commit/97cd07faa80afcf3076196dcb54650ad152fbfb2

Match new name for production configs in Doppler

---

core/cli/src/index.ts
lib/logger/src/styles.ts

Good to remove some of the abstraction magic from Tool Kit and also particularly useful when multiple tasks are run within a hook. Open to feedback on how this logger message should be formatted.

Print when a task is run to aid user visibility

---

lib/logger/src/helpers.ts

The [`RIS`](https://en.wikipedia.org/wiki/ANSI_escape_code#Fs_Escape_sequences) escape code is [used](https://github.com/microsoft/TypeScript/blob/61a96b1641abe24c4adc3633eb936df89eb991f2/src/compiler/sys.ts#L1604C39-L1604C44) by TypeScript's watch mode to clear the terminal before printing its watch logs. Rather than stripping all the (mostly useful) ANSI escape codes, let's just remove this one that can interfere when Tool Kit is printing logs from multiple tasks.

Strip ANSI escape codes that mess with terminal state, starting with RIS

---

core/create/src/prompts/options.ts
docs/migrating-to-tool-kit.md

fixing the below which were missed in the last PR:
- add `typeDescription` to all zod types
- add examples to ambiguous documentation
- fix invalid `npm build` command

fix: minor tweaks to documentation

---

orb/src/@orb.yml
orb/src/jobs/deploy-production.yml
orb/src/jobs/deploy-review.yml
orb/src/jobs/deploy-staging.yml

Technically every hook could have tasks that use the Doppler CLI via the doppler library, though we don't really want to have to spend time installing it for every job if we can help it and in (our current) reality only the hooks that deploy to Heroku need it in CI.
Fixes the `ENOENT` error we're currently [seeing](https://app.circleci.com/pipelines/github/Financial-Times/next-static/3054/workflows/a445164f-e884-40fd-a11d-c3470ac16c9d/jobs/11467/parallel-runs/0/steps/0-102) when deploying to Heroku in next-static.

Install doppler CLI for orb jobs that use it

---

lib/doppler/src/index.ts
lib/doppler/test/index.test.ts

We're still [failing](https://app.circleci.com/pipelines/github/Financial-Times/next-static/3070/workflows/600941b8-236f-4f6f-9039-b4831216d426/jobs/11488?invite=true#step-103-986_86) to find Doppler in CI as the command we're using to install the CLI only installs it [locally](https://github.com/ft-circleci-orbs/doppler-circleci-orb/blob/a156fa0809694c0d7ee0dba40224aef960a9f02a/src/scripts/install_doppler.sh#L23C148-L23C160) and not in your `$PATH`. I believe they avoid installing the binary as not all CircleCI images give you permission to do so. Rather than adding an option to the command (and potentially breaking some custom Customer Products projects if they run into those permissions issues), let's just check the local directory for the binary if we're running in CircleCI.

Use local doppler executable in CI

---

.circleci/config.yml
orb/src/jobs/setup.yml

This is no longer needed now all systems use atleast Node v16 which is bundled with npm v8.

CPP-925:  Stop force using npm 8 on circleci

---

plugins/heroku/src/setConfigVars.ts

This freaked me out when testing in next-static 😅

Only log Heroku config variable sync if not skipped due to Doppler migration

---

package-lock.json
plugins/npm/package.json
plugins/npm/src/tasks/npm-publish.ts
plugins/npm/test/npm-publish.test.ts

npm has started rejecting packages that attempt to publish with a different version defined in its' package.json. Turns out our plugin attempted to set the version in package.json but it wasn't saved. Packages have been publishing with a version number in package.json that differs to the version we state on npm.
This fix removes the use of the internal npm libraries and replaces it with using the cli directly.

CPP-1722: fix npm publish task

---

plugins/npm/src/tasks/npm-publish.ts

The npm publish task was giving the grouped logs heading as `npm [object Object]` which doesn't make it clear which of the tasks is currently happening.
This PR makes sure the correct npmTask value is being logged as the group heading.

fix(npm): add npmTask string to logger not task object

---

plugins/npm/src/tasks/npm-publish.ts
plugins/npm/test/npm-publish.test.ts

npm will try to set a git tag when running npm version. This is causing issues in CI as CircleCI is not setup with a git config (thankfully). We do not need npm to set a git tag and commit as this job will be running in response to a release tag being created on GitHub.

fix(npm): run npm version with --no-git-tag option

---

scripts/clean-up-packages.sh

This package is just a place to test Tool Kit code now and thus doesn't have a `package.json` of its own (though one can be added by the tester and it won't be tracked by git). Our clean up script [automatically](https://github.com/Financial-Times/dotcom-tool-kit/pull/64) removes any package without a `package.json` script to avoid 'zombie packages' but we can make an exception for the sandbox.

Allow sandbox directory to stay without package.json

---

.eslintrc.js
lib/types/src/hook.ts
plugins/heroku/test/setConfigVars.test.ts

option was always configured intending `_` prefixed vars to be allowed as unused but this conflicted with the Typescript plugin rule

Fix eslint no-unused-vars

---

core/cli/src/config.ts
core/cli/src/index.ts
core/cli/src/messages.ts
core/cli/src/plugin.ts

instead of just strings, which can easily be confused for strings from somewhere else.
in the very near future the entry point is not just going to be the plugin root; this refactor makes that easier.

refactor: use an EntryPoint object for tasks and hooks in the config

---

plugins/pa11y/.toolkitrc.yml
plugins/pa11y/readme.md
plugins/pa11y/src/tasks/pa11y.ts
plugins/pa11y/test/pa11y.test.ts

We are deprecating the Pa11y plugin as it is no longer recommended for accessibility testing within Customer Products. This PR adds the ability to run Pa11y locally (as an immediate step to support teams relying on the tool for now) then a deprecation warning along with suggestions for next steps.

CPP-1664: deprecate pa11y

---

plugins/serverless/src/tasks/deploy.ts
plugins/serverless/src/tasks/provision.ts

Previously was not awaiting on the spawned serverless processes so didn't throw an error if the child returned a non-zero exit code. Would prevent CI jobs like [this](https://app.circleci.com/pipelines/github/Financial-Times/next-url-management-api/1848/workflows/cff76aa5-90df-4465-80c0-7836571b7a48/jobs/7549?invite=true#step-106-1123_456) from incorrectly passing.

Confirm Serverless deployments have been successful before completing task

---

lib/doppler/src/index.ts

We [avoid](https://github.com/Financial-Times/dotcom-tool-kit/pull/497) falling back to Vault if Doppler options have been explicitly configured. However, Zod will always create an empty Doppler options object even if no options are specified (as the options are all optional in this case), meaning that we were never falling back to Vault.

Fix Doppler never falling back to Vault

---

lib/types/src/schema/plugins/circleci.ts

Don't love that this is a breaking change for the types package rather than for circleci but types is going to be getting a major version bump from other changes in the next branch anyway.

Bump default CircleCI node image used to be Node 18

---

package-lock.json
plugins/cypress/package.json
plugins/cypress/src/tasks/cypress.ts
plugins/cypress/tsconfig.json

I suspect this slipped through the [original migration](https://github.com/Financial-Times/dotcom-tool-kit/pull/458) as Vault support was [added](https://github.com/Financial-Times/dotcom-tool-kit/pull/460) to the plugin around the same time.

Add Doppler support to cypress plugin

---

package-lock.json
plugins/heroku/src/setConfigVars.ts
plugins/serverless/package.json
plugins/serverless/src/tasks/deploy.ts
plugins/serverless/src/tasks/provision.ts
plugins/serverless/tsconfig.json

Skip checking Vault for the `MIGRATED_TO_DOPPLER` flag if the Tool Kit config has already moved to using `@dotcom-tool-kit/doppler` options in the `serverless` plugin, to reflect the same change in the [`doppler`](https://github.com/Financial-Times/dotcom-tool-kit/blob/631cca2488dd2fe2689f0ad5189985492ef9263b/lib/doppler/src/index.ts#L118) and [`heroku`](https://github.com/Financial-Times/dotcom-tool-kit/blob/631cca2488dd2fe2689f0ad5189985492ef9263b/plugins/heroku/src/setConfigVars.ts#L22) plugins.
Also copy over the fix from #530 to the `heroku` plugin.

Skip Serverless check for Doppler flag in Vault if options already configured

---

core/create/src/prompts/oidc.ts

Doppler disallows lower case letters and hyphens in secret names so we can't store the AWS secrets using their respective repositories name suffixes; we have to transform them into Doppler-legal names first.

Accommodate for Doppler transforms when getting AWS secrets in migration script

---

plugins/typescript/.toolkitrc.yml
plugins/typescript/readme.md

this aligns it with eg the `babel` plugin, as well as where cp-content-pipeline was originally running it
HT @andygout for noticing this omission!

fix: add default assignment for build:ci and build:remote for TypescriptBuild

---

core/create/files/oidc-cloudformation.yml

Needed for Serverless deployments to be able to read Doppler secrets synced to AWS Parameter Store.

Add permission to read Parameter Store values to default OIDC role created by migration script

---

lib/logger/src/helpers.ts
plugins/jest/src/run-jest.ts
plugins/jest/tests/jest-plugin.test.ts

Have been trying to debug an issue that @GlynnPhillips raised a few months ago about the `jest` plugin [failing](https://app.circleci.com/pipelines/github/Financial-Times/next-profile/12460/workflows/50fe1cd9-b326-45d6-87b7-cb15abd9469c/jobs/50449?invite=true#step-102-198909_49) unexpectedly with an unhelpful error message. Ultimately, it looks like the underlying problem is a memory leak within their test suite causing the CircleCI executor to kill the process due to an out-of-memory exception (with Tool Kit running causing the memory usage in the container to be tipped over the edge.) This can't be solved from Tool Kit, however I spotted a few issues which could be fixed by us:
1. log terminations of sub processes by signals properly
2. limit the number of spawned worker threads to the …

Improve behaviour after testing runaway Jest tests

---

core/cli/src/config.ts
core/cli/src/install.ts
core/cli/src/messages.ts
core/cli/src/plugin.ts
core/cli/src/rc-file.ts
core/create/src/index.ts
lib/types/src/hook.ts
lib/types/src/hooks.ts
lib/types/src/index.ts
lib/types/src/schema/hooks/package-json.ts
lib/types/src/validated.ts
package-lock.json
plugins/circleci/.toolkitrc.yml
plugins/circleci/src/circleci-config.ts
plugins/package-json-hook/package.json
plugins/package-json-hook/src/package-json-helper.ts
plugins/package-json-hook/test/index.test.ts

- plugins specify which hooks they want to instatiate with particular options
- these installations are merged into a list of (potentially-conflicting) installations, based on conflict resolution handlers the hook classes provide (with some basic fallback logic)
- the installations are lazily reduced and loaded when checking hook installations and installing them
- implement a sensible options structure for the `PackageJson` hook

reinstate hook options

---

core/cli/src/config.ts
core/cli/src/install.ts
docs/custom-plugins.md
docs/developing-tool-kit.md
lib/types/src/hook.ts
plugins/circleci/src/circleci-config.ts
plugins/circleci/test/circleci-config.test.ts
plugins/package-json-hook/src/package-json-helper.ts
plugins/package-json-hook/test/index.test.ts

thanks for the suggestion @cerdfied!
i've gone for `isInstalled` rather than your suggestion of `checkInstalled` as this method is kind of a predicate? happy to bikeshed though. if this were Ruby i'd have called it `installed?`

refactor!: rename Hook#check to Hook#isInstalled

---

core/create/src/index.ts
core/create/src/prompts/confirmation.ts
core/create/src/prompts/main.ts

We don't want people committing the `.toolkitstate` directory, so let's add make sure it's ignored by git in the migration script.

CPP-1505 Add option in migration script to add .toolkitstate directory to gitignore

---

core/create/src/index.ts
core/create/src/prompts/confirmation.ts
core/create/src/prompts/main.ts

n-gage would copy a default ESLint config into your project but [only if `.eslintrc.js` was in your `.gitignore`](https://github.com/Financial-Times/n-gage/blob/1edbe16b1f49058b534c0bd117ce5bd0f17d13c2/src/tasks/install.mk#L55). This means that many n-gage projects don't have committed ESLint configuration. The Tool Kit migration script will set up our own recommended ESLint config (pulling in the settings from [eslint-config-next](https://github.com/Financial-Times/eslint-config-next)) but we should also make sure the config isn't also ignored by git.

CPP-1776 Add option to remove ESLint config from gitignore

---

core/create/src/prompts/main.ts

upload-assets-to-s3 is already included by frontend-app, and it's basically pointless for any other kind of repo (unless you definitely know you need it, in which case i think having to install it manually is fine?).
leaving this in (especially having it checked by default if you've selected frontend-app) causes unnecessary duplicate plugins.

fix: don't suggest upload-assets-to-s3 in additional plugin prompt

---

core/create/src/bizOps.ts
core/create/src/makefile.ts
core/create/src/prompts/systemCode.ts
package-lock.json

Main change is to fix the script crashing if you try to migrate a component/package without a Biz Ops code, a bug that was introduced when we started guessing Biz Ops codes in #553.

Migration script fixes from n-test migration

---

docs/migrating-to-tool-kit.md
readme.md

I always include the `@latest` specifier when people ask the easiest way to migrate to Tool Kit these days, but I never got round to updating the documentation so that this wasn't hidden knowledge. Finally pushed by @apaleslimghost posting about this paper cut!

Recommend forcing npx to use the latest version of the migration script

---

plugins/cypress/src/tasks/cypress.ts

We should be able to get the Cypress base URL from either Doppler or the Tool Kit config, but the setting in your config should override what's in Doppler as this will allow users to test out a different URL in a separate branch if needed. [Highlighted](https://financialtimes.slack.com/archives/C3TJ6KXEU/p1707159162412489) by @debugwand.
This is a breaking change as people may have been relying on the previous override behaviour (although only cp-content-pipeline seems to be doing so at this time).

Allow Tool Kit option to override Doppler secret when setting Cypress base URL

---

plugins/cypress/src/tasks/cypress.ts

This fixes the CypressCi task [always logging](https://app.circleci.com/pipelines/github/Financial-Times/next-newsletter-signup/4926/workflows/5a200d63-ca98-41d3-976c-69fc04cc60d9/jobs/18402?invite=true#step-102-808_45) that the URL it's testing is `undefined`.

Use correct name when logging Cypress URL in CI

---

core/create/src/index.ts
core/create/src/prompts/oidc.ts

Even though the Tool Kit and Doppler migrations are separate, it makes sense to preempt the latter migration here to save confusing error messages and additional PRs to aws-composer repositories. [Suggested](https://financialtimes.slack.com/archives/C3TJ6KXEU/p1707737143735799?thread_ts=1707476589.356479&cid=C3TJ6KXEU) by @danieleruiz.

CPP-1941 Include permission to read Doppler secrets when importing deployment role during migration

---

core/create/src/prompts/oidc.ts

Doppler requires all IAM user keys it rotates automatically to use the same suffix with a custom prefix. Our suffix was previously the name of the AWS account the user was associated with but now that needs to be the prefix. You can see the new secrets in the [`dotcom-tool-kit` `prod` config](https://dashboard.doppler.com/workplace/99fbb11f5bea112e94dd/projects/dotcom-tool-kit/configs/prod). These secrets will probably never be needed seeing as the migration has been done but it made sense to use them as a test case of Doppler-managed secrets!

Use different format for Doppler-managed AWS keys to read previous IAM permissions

---

core/cli/src/plugin.ts
core/cli/src/plugin/merge-commands.ts
core/cli/src/plugin/reduce-installations.ts
core/cli/src/rc-file.ts
core/create/src/index.ts
lib/plugin/src/index.ts

this Should<sup>TM</sup> allow most<sup>[citation needed]</sup> apps' toolkitrcs to load without any changes, just by updating Tool Kit
- renames the new .toolkitrc field `hooks` to `options.hooks`
- reënables specifying the old-style `hooks` in .toolkitrc, treating it as equivalent to the new `commands`, printing a warning

Slightly more backwards compatible

---

core/cli/src/rc-file.ts

old `.toolkitrc`s contain `options` with just plugin options. these are now nested under `options.plugins`. if an `options` is non-empty, but doesn't contain any of the new top-level fields, assume it's old-style, and nest it.
**nb** this probably won't actually work in most cases, as the options are all moving around in #570. but we'll at least get semi-useful schema errors. maybe?

Backwards compatible .toolkitrc options field

---

core/cli/src/config.ts
core/cli/src/messages.ts

since there's no concept of "defining" a command like we had with hooks, we can remove this.

fix: remove check for undefined commands

---

core/cli/src/tasks.ts

chore: remove duplicate runInit call in runTasks

---

plugins/circleci/src/circleci-config.ts
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/test/files/with-hook/.circleci/config.yml

This creates much simpler config for the majority of projects (i.e., projects that don't need to test against multiple versions of Node.) For example, here's the diff for next-static's config after its config is reinstalled:
```patch
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 9aded16..aad31b5 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,42 +32,30 @@ workflows:
branches:
only: /(^renovate-.*|^nori/.*)/
- tool-kit/setup:
-          name: tool-kit/setup-<< matrix.executor >>
+          executor: node
requires:
- checkout
- waiting-for-approval
-          matrix:
-            parameters:
-              executor:
-                - node
filters:
tags:
only: /^v\d+\.\d+\.\d+(-.+)?/
- tool-kit/build:
-          name: tool-kit/build-<< matrix.executor >> …
```

Don't generate matrices in CircleCI config if only one Node version is being tested

---

core/cli/src/index.ts
plugins/eslint/src/tasks/eslint.ts

as requested by @GlynnPhillips. there's currently no way to exit tasks early on error and _not_ run subsequent tasks in the command's task array.

feat: exit running tasks early if the task threw an error with an exitCode

---

core/cli/package.json
core/cli/src/config.ts
core/cli/src/plugin.ts
core/cli/src/plugin/options.ts
core/cli/src/rc-file.ts
core/cli/test/index.test.ts
core/cli/test/options.test.ts
core/create/package.json
core/create/src/index.ts
lib/config/src/index.ts
package-lock.json
plugins/circleci-deploy/.toolkitrc.yml

These two custom YAML tags allow us to define all the different combinations of Serverless and Cypress configuration needed to be added to CircleCI config. These were previously defined in JavaScript functions that were hard to compose but now they can be specified in a declarative, readable syntax along with the rest of the config.
There are two tags available currently: `!toolkit/option` will substitute the specified option as a string into your config, whilst `!toolkit/defined` will conditionally include its value in your config if the specified option is defined. You can see how they can be used in the test cases and in `circleci-deploy`'s updated config (scroll down all the way to the end of the PR for that!)

CPP-2041 CPP-2030 Add support for tags in Tool Kit config that resolve to values of options

---

core/cli/bin/run
core/cli/src/config.ts
core/cli/src/install.ts
core/cli/src/plugin/options.ts
core/cli/src/plugin/reduce-installations.ts
core/cli/src/rc-file.ts
lib/config/src/index.ts
lib/schemas/src/plugins/lint-staged-npm.ts
plugins/heroku/.toolkitrc.yml
plugins/husky-npm/.toolkitrc.yml
plugins/lint-staged-npm/.toolkitrc.yml
plugins/npm/.toolkitrc.yml
plugins/package-json-hook/src/package-json-helper.ts
plugins/prettier/.toolkitrc.yml

Along with adding the hook options so that plugins that use `package-json-hook`'s `PackageJson` hook will now install their commands into the user's `package.json`, I've also fixed any bugs I found with the Tool Kit code that was preventing the installation from running successfully. I used `next-url-mgmt-service` (with the `lint-staged-npm` plugin added) as a test case.

CPP-1748 Define hook options for all packages previously using PackageJsonHelper hook

---

core/cli/src/tasks.ts
plugins/package-json-hook/src/package-json-helper.ts

The build is currently [failing](https://app.circleci.com/pipelines/github/Financial-Times/experimentation-api/4/workflows/6a001f36-f504-4c29-8db6-0d62ab83b180/jobs/18) _because of us!!_ I'll cut another prerelease for the relevant packages after this is merged.

Fixes to next to unblock experimentation-api

---

core/cli/src/tasks.ts

Should fix experimentation-api [build failures](https://app.circleci.com/pipelines/github/Financial-Times/experimentation-api/36/workflows/9b061683-121b-4f49-a6c4-2fbce1e0c28c/jobs/202).

Fix Task options not being unwrapped when returned from Zod

---

core/cli/package.json
core/cli/src/plugin.ts
core/cli/src/plugin/entry-point.ts
core/cli/src/tasks.ts
package-lock.json

This fixes some issues where custom plugins couldn't be loaded nor would their task options be passed to them. Tested with experimentation-api's [WIP custom plugin](https://github.com/Financial-Times/experimentation-api/pull/4) for Node test runner.

Fix issues with custom plugins

---

lib/logger/src/format.ts
lib/logger/src/helpers.ts

This partially reverts https://github.com/Financial-Times/dotcom-tool-kit/commit/d1374d143d75d9abc018fb7c3a62a97be10c432d, which I think was a mistake as we already remove the EOL character normally added by `winston`, and we skip appending a newline character to messages if it has a `process` attribute. So it meant that the only newlines that would be preserved were ones that happened to not be at the end (or start) of a stream flush.
Running the `Mocha` task in next-static before this change:
Running the `Mocha` task in next-static after this change:
And here is what the output looks like when `mocha` is run directly instead. Note the matching amount of whitespace.

Fix lack of newlines in subprocess logging

---

core/create/files/oidc-cloudformation.yml

We've changed the permissions in our OIDC nested stack role, in order to remove legacy role assumptions by the old ft-engineer and ft-iam-admin roles. This PR updates to the latest template (v2).
The v2 template has slightly differing permissions, but should affect apps role assumptions, and there should be no effect on deployments.
PR for template changes here: https://github.com/Financial-Times/circleci-nested-stack-template/pull/25

change nested stack template to v2

---

commitlint.config.js

backstage: disallow chore commits, introduce backstage commits

---

package-lock.json
plugins/circleci/src/circleci-config.ts

This resolves an issue found when (experimentally) migrating [user-agent-node](https://github.com/Financial-Times/user-agent-node/tree/tool-kit-prerelease) to the Tool Kit pre-release. For instance, a job to run a build will now be named `tool-kit/build-<< matrix.executor >>` instead of `build-<< matrix.executor >>`, which is important as other jobs were already referring to it by the former name.

Use correct name for jobs in a matrix

---

lib/logger/src/format.ts
lib/logger/src/helpers.ts

Fix subprocess logging (but on main this time)

---

package-lock.json
plugins/circleci-deploy/src/index.ts
plugins/circleci/src/circleci-config.ts

We are already running staging jobs on tagged releases, so we don't need to run review jobs too. In addition, the `HerokuReview` task will fail as it can't find a branch to associate the review app with. For an example of why this is a problem, see next-router's CI [workflow](https://app.circleci.com/pipelines/github/Financial-Times/next-router/3073/workflows/8deeedd2-4e71-4916-86bd-99c50e2f64d8) with its unnecessary `tool-kit/deploy-review-node` branch.

Don't run review jobs on tagged releases

---

core/cli/src/tasks.ts
package-lock.json

`loadTasks` returned a `Record<string, Task>`, meaning that a command with multiple instances of the same task would just load the last created instance (with the last specified options), meaning tasks couldn't be called multiple times with different options.

fix: allow multiple instances of task with different options

---

core/cli/src/tasks.ts
lib/base/src/task.ts
plugins/eslint/src/tasks/eslint.ts
plugins/eslint/test/tasks/eslint.test.ts
plugins/prettier/src/tasks/prettier.ts
plugins/prettier/test/tasks/prettier.test.ts

group the `files` argument for `Task.run` into a "task context" object so we can pass more things into tasks later on. extracted from #630

refactor!: pass task files in as part of a run context object

---

plugins/circleci-deploy/.toolkitrc.yml

Adds back some missing Serverless parameters to the `deploy-review` job in CircleCI.
Fixes the issue reported in https://github.com/Financial-Times/cp-healthchecks/pull/5.

Fix up some some missing options in CircleCI config

---

.circleci/config.yml
core/cli/src/config.ts
plugins/circleci-deploy/.toolkitrc.yml
plugins/circleci/test/files/with-hook/.circleci/config.yml
plugins/frontend-app/.toolkitrc.yml
plugins/webpack/.toolkitrc.yml

These should unblock apps experiencing issues with migrating to the new Tool Kit major version.

Miscellaneous fixes for major release

---

core/cli/src/tasks.ts

split from #630. allows running tasks from a previously-loaded config.

refactor: split out task running and config loading

---

.circleci/config.yml

We had previously [removed the filter for Renovate and nori PRs](https://github.com/Financial-Times/dotcom-tool-kit/commit/0716ad29155fe605f705fd47bfdd8f7eadbb98b3) but not the workflow that only ran when the filter was true. Without the filter it is now running unconditionally for every PR, causing duplicated CI work.

Remove Renovate/nori workflow

---

core/cli/package.json
core/cli/tsconfig.json
package-lock.json

noticed by @rowanmanning. in practice, most repos install a plugin that depends on `state`, which is why we haven't noticed this until now.
we should probably set up `eslint-plugin-import` to catch this!

fix(cli): add missing dependency on @dotcom-tool-kit/state

---

core/cli/src/install.ts
core/cli/src/messages.ts
core/cli/src/plugin/reduce-installations.ts
core/cli/test/index.test.ts

We were previously throwing when we encountered an unknown hook option or an invalid hook option. This resulted in a cryptic stacktrace without much for the user to use to fix the issue. Instead, let's wrap the function in a `Validated` and use properly formatted error messages to handle these errors.

CPP-2067 Gracefully handle hook installation errors

---

core/cli/src/plugin/reduce-installations.ts

This wasn't caught by TypeScript because `options` effectively has an `any` type. It was causing weird conflict errors because the options were nested one level deeper, messing with the conflict detection logic. This makes me happy because it explains the weird testing behaviour I was trying to fix in c5ea614d4f0b4e074459a1f9cdead82edd63042d :) We still don't need to parse the options twice so that commit doesn't need to be reverted.

Fix spurious conflict errors

---

core/cli/bin/run

winston seems to eat the last log line for some reason?

fix: log an extra newline after error details

---

lib/schemas/src/moved-plugin-options.ts
lib/schemas/src/plugins/heroku.ts
lib/schemas/src/plugins/serverless.ts
lib/schemas/src/prompts.ts

when migrating from v3, Tool Kit will happily accept these options, even though they're not present in the plugin schema (because it's not strict). this provides helpful error messages to instruct the user that these options need to be moved (which will make the migration guide easier to follow).

feat(schemas): add validation warnings for plugin options that moved to task options

---

core/cli/src/plugin/resolve-root.ts
core/cli/test/resolve-root.test.ts

resolving package.json works fine for built-in plugins, but for custom plugins this effectively means they need to have an index.js, which most won't any more. resolve the .toolkitrc.yml, which every built-in and custom plugin must have

CPP-2275: resolve a plugin's .toolkitrc.yml

---

core/cli/src/plugin/require-resolve.ts
core/cli/src/plugin/resolve-root.ts
core/cli/test/resolve-root.test.ts

and do some cursed things to work around Jest's different behaviour for `require.resolve` in the tests

preserve relative paths in resolveRoot to fix custom plugin loading

---

package-lock.json
package.json
tsconfig.settings.json

This should have been done as part of us dropping support for Node 16 as this allows us to reduce the number of polyfills generated. It also means we can start generating ESM files if we want by updating their `package.json` config to use the `module` `type`. The change to the `module` setting in `tsconfig.json` requires us to bump ts-jest to a new minor version that supports the option.
Split from #703 as it felt like it slightly tangential to the change to the `@types/node` versions.

Bump TypeScript config to Node 18 version

---

release-please-config.json

We forgot to add the new plugin to the Release Please config so it didn't get published.

backstage: ensure the cloudsmith plugin publishes

---

core/cli/src/plugin/entry-point.ts

We [recently bumped](https://github.com/Financial-Times/dotcom-tool-kit/pull/733) our tsconfig base to a newer version that switched the [`module`](https://www.typescriptlang.org/tsconfig/#module) setting from `commonjs` to `node16`. In most cases this had no effect on the generated code, as CommonJS code would still be emitted for files that aren't specified to be ESM modules. However, the setting also changes dynamic imports within CJS code to be preserved when emitted instead of being transpiled to a (wrapped) call to `require`.
Let's explicitly use `require` instead of a dynamic import when loading entrypoints to avoid CJS/ESM incompatibilities. I believe we had [previously](https://github.com/Financial-Times/dotcom-tool-kit/pull/241) opted for a dynamic import in order to get plugins …

Make sure to load plugins with CJS require instead of ESM import

---

plugins/cloudsmith/.toolkitrc.yml

This option is validated and we're required to set it to an array. Setting it to an empty array doesn't override the existing `requires` - the array gets merged together.
[See schema here](https://github.com/Financial-Times/dotcom-tool-kit/blob/de09e954ea4c73d866d3522ad84c4117c3f51ae8/lib/schemas/src/hooks/circleci.ts#L48). I didn't want to make this optional just in case that breaks something else.

fix: add the requires property to CI jobs

---

plugins/upload-assets-to-s3/README.md

Correct name of `UploadAssetsToS3` task (capital `S3`)

docs: fix name of UploadAssetsToS3

---

package-lock.json
plugins/n-test/package.json
plugins/n-test/src/tasks/n-test.ts
plugins/n-test/test/tasks/n-test.test.ts
plugins/n-test/tsconfig.json

This line, which appeared in c070cc2, breaks test running. This is because n-test already prepends `process.cwd()` so it doubles up. This results in something like:
```
/Users/me/code/project/Users/me/code/project/test/smoke.js
```
@apaleslimghost suggested replacing it with an error if you're not running n-test from the current working directory. I copied it loosely from 81ebda7 where we're doing the same for the nodemon plugin.
I didn't want to make a change to n-test to get a quick fix rolled out, however that's probably the better long-term solution: n-test should use `path.resolve()` instead of `path.join()`, however that might break someone else's usage if they have a workaround in place 🤷

fix: stop adding CWD to the n-test config path

---

lib/logger/package.json
package-lock.json

The logger module depends on `chalk` however it's not explicitly installed - it's installed by `@apaleslimghost/boxen`. This causes Tool Kit to wrongly depend on a more recent (and ESM only) version of Chalk if a project installs it.
The example I encountered: our project is installing `@commitlint/cli@19.6.1` which depends on `chalk@v5`. Tool Kit, on the other hand, seems to rely on `chalk@v4` transititvely - this version still supports CommonJS.
```
project@0.0.0
├─┬ @commitlint/cli@19.6.1
│ └─┬ @commitlint/format@19.5.0
│   └── chalk@5.4.1
└─┬ @dotcom-tool-kit/circleci@7.3.2
└─┬ @dotcom-tool-kit/logger@4.1.0
└─┬ @apaleslimghost/boxen@5.1.3
└── chalk@4.1.2
```
`@dotcom-tool-kit/logger` imports `chalk` here:
https://github.com/Financial-Times/dotcom-tool-kit/blob/01031177495ac7c483bbcb23b …

fix: stop using chalk as a transitive dependency

---

package-lock.json
plugins/docker/package.json
plugins/docker/src/image-info.ts
plugins/docker/tsconfig.json

tasks should be agnostic of where they're running, we use state so plugins like `circleci` can provide information about the environment without coupling tasks to the platform

feat(docker): read ci build info from state instead of using env vars directly

---

lib/schemas/src/hooks/circleci.ts
plugins/circleci-deploy/test/__snapshots__/circleci-deploy.test.ts.snap
plugins/circleci-deploy/test/circleci-deploy.test.ts
plugins/circleci-npm/test/__snapshots__/circleci-npm.test.ts.snap
plugins/circleci-npm/test/circleci-npm.test.ts
plugins/circleci/src/circleci-config.ts
plugins/circleci/test/__snapshots__/circleci-config.test.ts.snap
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/test/files/.toolkitrc.yml

the `.partial()` on the hook option objects is overriding the `.default()` on their properties.
short of splitting the schema into an incoming options schema that's meant to be merged from
multiple sources, and an outgoing schema for the final hook options, this is the most
straightforward way of doing this.

CPP-2322 fix circleci option defaults

---

package-lock.json
plugins/mocha/package.json

mocha v11 has only one breaking change - dropping support for Node.js 14 and 16. We should widen the version range to allow our projects to use it.

feat: widen semver range for mocha

---

lib/state/src/index.ts
plugins/docker/src/image-info.ts
plugins/docker/src/tasks/build.ts
plugins/docker/src/tasks/push.ts

We will need the built image names and tags in order to deploy via Hako. This involved a bit of refactoring of the tag generation so that we weren't duplicating stuff. We're using the CI build number for deploys for now but this can change with no issue later if we change our minds.

Store pushed Docker images in state

---

core/cli/src/install.ts
lib/schemas/src/hooks/circleci.ts
plugins/circleci/src/circleci-config.ts
plugins/circleci/test/circleci-config.test.ts
plugins/circleci/test/files/unmanaged/with-workflow-job/.circleci/config.yml

Our initial 4.0 release of Tool Kit only contained minimal support for defining custom jobs in CircleCI. They didn't define the executor the job would run in, resulting in CircleCI validation errors unless they were added explicitly in a `custom` block, so even calling it 'minimal support' might be a stretch. This PR adds proper support for the execution property, as well as adding a `splitIntoMatrix` option to jobs which works the same as it does for workflow jobs. Efforts have also been made to refactor the code so that it's easier to follow.
This now allows us to generate a CircleCI config for next-preflight using Tool Kit config exclusively without manual intervention.
Closes #740, as this PR carries on from the changes made in that PR.

CPP-2313 Add proper support for custom jobs in CircleCI

---

orb/src/@orb.yml

Code Management just pushed out a hotfix for the orb to account for an API change with Cloudsmith. Let's not specify the patch version when specifying their orb so that CircleCI will always use the latest patch (of the pinned minor version.)
Code Management [suggested](https://financialtimes.enterprise.slack.com/archives/C02ST9MNV0S/p1738008489052549) to do this themselves so we can assume they'll respect semver guidelines.

Automatically use latest patch version of cloudsmith-oidc orb in our own orb

---

package.json

backstage: remove check-engine preinstall script

---

plugins/docker/.toolkitrc.yml
plugins/docker/src/tasks/auth-cloudsmith.ts
plugins/docker/src/tasks/push.ts

We hit an annoying roadblock here. Because all the auth is done as part of the `DockerPush` task, we aren't authenticated when we try to pull a built image as part of the production deploy.
I think it's sensible to pull the auth out of the `DockerPush` task. Unfortunately this is a breaking change, but that's why we went with an `0.1.0` release originally.

feat!: move docker auth to a new task

---

lib/state/src/index.ts
plugins/docker/src/tasks/push.ts
plugins/hako/src/tasks/deploy.ts

We were seeing some issues with using "ci" state because it's written to in multiple jobs - we can't rely on docker images being available when we reach deploy-prod.

fix: use a new "docker" state for pushed images

---

plugins/circleci-deploy/test/__snapshots__/circleci-deploy.test.ts.snap
plugins/circleci-npm/test/__snapshots__/circleci-npm.test.ts.snap
plugins/circleci/src/circleci-config.ts
plugins/circleci/test/__snapshots__/circleci-config.test.ts.snap
plugins/circleci/test/circleci-config.test.ts

The persistence job step that is installed into custom jobs was calling CircleCI's `persist_to_workspace` command directly rather than the Tool Kit orb abstraction, and the attachment job step was doing the same except with the kebab casing of the Tool Kit command's name which meant it would create an invalid config file. Using the commands directly may have originally been intended as a step towards removing our use of the Tool Kit orb, but this is no longer a change that is currently planned.
This hasn't caused any problems as of yet as the attachment command is only installed for custom jobs which aren't particularly used currently.

Use correct Tool Kit workspace commands in CircleCI jobs

---

package-lock.json
scripts/generate-docs.js

Based on a code review suggestion, I updated the name of the field returned from `importEntryPoint` from `entryPoint` to `baseClass` as the previous name was overloading a parameter name that served a different purpose. I checked for build errors to find places where the name needed to be updated, but of course the `generate-docs.js` script is written in JavaScript and not checked by TypeScript, so I missed that the change needed to be reflected in the script too. This is now fixed and won't block git hooks from passing.

Fix reference to old entry point field name in generate-docs script

---

core/cli/test/__snapshots__/config.test.ts.snap
package-lock.json
plugins/circleci-deploy/.toolkitrc.yml
plugins/circleci-deploy/test/__snapshots__/circleci-deploy.test.ts.snap

Noticed when I was double-checking the [generated CircleCI config](https://github.com/Financial-Times/next-preflight/pull/871/files) for next-preflight. Was originally introduced in #670, specifically the [force push](https://github.com/Financial-Times/dotcom-tool-kit/compare/26466f85c52753ee69ee2f142db484473363b97c..3e2970e4343ce34267a7cee4e8983d713a98df09) made soon after the PR was created.
I _must_ have got confused when making the changes in the amended commit and thought we were still the old negated 'skipOnRelease' option instead. I really can't think of any other reason why it's configured like this.

_Do_ run production deployment jobs on tagged releases

---

plugins/docker/src/image-info.ts
plugins/docker/src/tasks/build.ts

This removes a lot of the tags we've been adding to images, reducing it down to only the tag we use for deployment. It replaces many of these tags with the labels outlined in the [Standard Labels for FT Container Images proposal](https://docs.google.com/document/d/1USDbK4ptBe4VRW_3Ujv0RCgrD9JOhMHT1JjImQGvmRQ/edit).

feat!: adopt standard labels for container images

---

release-please-config.json

This will allow release-please to release the plugin.

Add monorepo plugin to release-please config

---

core/cli/src/plugin/reduce-installations.ts
package-lock.json
plugins/circleci-npm/test/circleci-npm.test.ts

There was a bug where if any hook's options were overridden at the top level plugin (i.e., the `.toolkitrc.yml` at a project's root) then only that hook would run, regardless of whether hooks were defined in transitive plugins. This was because the code path taken when there were hook options in a plugin was different and would only return hooks with options defined.
This isn't usually an issue as none of the plugins typically responsible for defining hook options would be parents of plugins that defined other hooks, so hooks were never discarded and were merged as siblings by further plugin parents. This becomes a more obvious issue if a user was to define top-level hook options, as by definition the app root has no parent plugins and therefore no siblings either.

Make sure to run all install hooks when options are set at the app root

---

package-lock.json
plugins/serverless/package.json

The range now includes v13. This [version](https://github.com/dherault/serverless-offline/releases/tag/v13.0.0) drops support for Node 16 (which we've also dropped support for) and no longer will try to install `node-fetch` if fetch is not present.
This is important for us as it uses a top-level await to import `node-fetch` which causes issues when running with Node 22. Serverless will typically try to require a module then fall back to an ESM import if that fails, but with Node 22 `require`'ing a module that has any top level awaits will cause an exception to be thrown instead.
Adding v13 to the range of permissible versions will allow consumers to update their version of `serverless-offline` in order to avoid this issue as part of a Node 22 migration. Note that the later v14 is not …

Widen dependency range for serverless-offline peer dependency

---

plugins/hako/src/tasks/deploy.ts

We now generate a hash based on the branch name and use this as a suffix on review app names. This means a couple of things:
1. Review app names are predictable
2. Only one review app will be created per branch, with future commits to that branch updating the existing review app instead of deploying another one
This is good for a couple of reasons:
We can now hand the review app URL off to future jobs. This is important for the n-test and cyprus plugins which expect a URL in the `review` or `staging` state.
We will stop creating a new review app for every commit, we're already seeing way too many review apps get created which is a problem while we don't have automatic deletion of old review apps.
Changes to a PR will deploy faster because most of the review app CloudFormation stack will …

fix: make review app URLs predictable

---

package-lock.json
plugins/node-test/package.json

Turns out `npm init` strips `node-` from the start of the name and we missed this.

fix: correct the node-test plugin name

---

plugins/hako/src/tasks/deploy.ts

All the changes since the last release are [here](https://github.com/Financial-Times/hako-cli/compare/v0.2.0-beta...v0.2.3-beta). I don't think there's anything _particularly_ relevant to us but I'm nervous about using an old version because of compatibility issues.

Bump to latest hako image

---

lib/logger/src/helpers.ts
lib/logger/src/index.ts
package-lock.json
plugins/node-test/package.json
plugins/node-test/src/tasks/node-test.ts
plugins/node-test/tsconfig.json

The `node-test` plugin now pipes the output from the `TestStream` into a winston log we've set up. This means that all the standard logging formatting is now applied to these logs rather instead of streaming directly to `stdout`. In particular, this means the task/process prefix is applied so the logs can be differentiated from logs by other tasks.
I refactored the helpers in the `logger` module to do this, pulling out a function from `hookFork` into its own helper. This will mean it will be easier to hook into Node streams in future plugins.

Improve logging for the `node-test` plugin

---

.github/dependabot.yml

We never enabled Dependabot/the auto merger in this repository! Let's get it configured.

Add Dependabot config to group updates

---

package-lock.json
package.json

This was [originally put in place](https://github.com/Financial-Times/dotcom-tool-kit/pull/361) to work around some TypeScript compiler errors when importing a `PartialDeep` type from the `circleci` plugin. Since Tool Kit v4, hook options are defined in config rather than in code so this concern is no longer relevant.
Additionally, it was causing Dependabot [to fail](https://github.com/Financial-Times/dotcom-tool-kit/actions/runs/14353765591/job/40238366188#step:3:12229) as it couldn't handle the override.

Drop `type-fest` version override

---

.github/dependabot.yml

They're currently grouped with all other dev dependency updates but this will lead them to going out of sync with the packages they define types for. If we don't bucket them in the `development-dependencies` group then Dependabot should fall back to its [default behaviour](https://github.com/dependabot/dependabot-core/pull/5000) of grouping them with their counterpart packages.

Group `@type` definition updates with counterparts instead of with other development dependencies

---

.github/dependabot.yml

Tweak the [`open-pull-requests-limit`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#open-pull-requests-limit-) value.
The default of 5 is usually a good choice to reduce PR noise, but it's problematic when we're quite behind on dependency versions and some dependencies can only be safely updated once others have been updated. Hopefully, this will allow us to more efficiently go through updates as part of some BAU work until we've reached a status quo where we've largely caught up or triaged updates.

Increase number of allowed open dependabot PRs

---

core/cli/package.json
package-lock.json
plugins/circleci/package.json
plugins/prettier/package.json

Dependabot has created PRs for all of these dependencies and thus highlighted how they aren't actually used anywhere. `hook-std` was initially used when prototyping hooking logs into stdout, we've removed `js-yaml` already so don't need `@types/js-yaml` and `chai` seems to have just been added accidentally.

Delete unused dependencies from packages

---

package-lock.json
plugins/next-router/package.json

All the new major version does is drop support for Node 18 and Node 20. I think dropping support for Node 20 is a mistake that will be remedied in due course. Whilst Tool Kit hasn't dropped support for Node 18 yet we're right on the precipice of doing so (Node 18 is EOL at the end of the month) and besides next-router isn't using any non-Node 18 code yet. Keeping this dependency up to date is more important because changes are regularly being made to next-router and teams will want to keep their local versions in sync with the deployed service.

Bump to new major version of next-router package

---

plugins/hako/src/tasks/deploy.ts

Switches us to use [hako v0.2.5-beta](https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.5-beta) by default. In future we'll make this configurable but for now let's keep bumping.

feat: update hako to v0.2.5-beta

---

package-lock.json
plugins/hako/src/tasks/deploy.ts

Switches us to use [hako v0.2.6-beta](https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.6-beta) by default. In future we'll make this configurable but for now let's keep bumping.

feat: update hako to v0.2.6-beta

---

plugins/circleci/src/schemas/plugin.ts

We need to set the `passthrough` field so that zod doesn't strip unrecognised keys before passing the options to the refinement function. This is what we did for other option deprecation errors but was missed with this one.

Fix error for using old `nodeVersion` option in `circleci` plugin not throwing

---

plugins/aws/src/tasks/assume-role.ts
plugins/docker/src/tasks/auth-cloudsmith.ts
plugins/docker/src/tasks/build.ts
plugins/docker/src/tasks/push.ts
plugins/hako/src/tasks/deploy.ts
plugins/node-test/src/tasks/node-test.ts

Many of the tasks added by CP Reliability rethrow errors to ensure that we catch and explain errors that are outside of our control, e.g. loading a file that doesn't exist. We wanted these to be Tool Kit errors so that we get nice error rendering. We also wanted to just throw normal errors for things like validation errors or missing data.
The issue is that we didn't know about the `exitCode` on Tool Kit error. This means that any `Error` instances that we wrap will not exit the command early. This is most notable in the Docker build/deploy commands: If the Docker build fails then we still move on to try and deploy even though there's no point. This results in longer build times, unnecessary tasks being run, and confusing error messages.
We now no longer wrap Tool Kit errors themselves, …

fix: ensure tasks exit the command on failure

---

plugins/hako/src/tasks/delete.ts

The `HakoDelete` task was calling `hako image delete ...` rather than `hako app delete ...`. The former is not a valid hako command and will result in an error. I believe this was just a mistake when I wrote the code as we _do_ want to delete the canary app from AWS, not the current task/image.

Correct hako subcommand when deleting ephemeral apps

---

core/cli/bin/run
core/cli/src/index.ts

would have been useful when diagnosing [CPP-2561](https://financialtimes.atlassian.net/browse/CPP-2561), and will help with visibility for users on what options will be different when we release the breaking change fix for that
[CPP-2561]: https://financialtimes.atlassian.net/browse/CPP-2561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cli): add a --printMergedOptions flag

---

plugins/hako/src/hako.ts

- https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.10-beta
- https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.11-beta
- https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.12-beta
- https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.13-beta
Shouldn't be any breaking changes for us in these releases, but will add support for new features that teams want.

Upgrade Hako image from 0.2.9 to 0.2.13

---

plugins/hako/src/hako.ts

https://github.com/Financial-Times/hako-cli/releases/tag/v0.2.14-beta

feat(hako): bump hako to 0.2.14
