plugins/prettier/package.json

i should probably take another look at #54 huh

CPP-727 fix prettier plugin dependencies

---

plugins/circleci/src/circleci-config.ts

persist entire workspace in initial checkout command

---

.circleci/config.yml

Following the guide for https://docs.google.com/document/d/1v9RkIk8IaykvzUqHp39bLX1_FVWqBZWI-Wz-GFWFfgw/edit#

Add context for npm auth token

---

docs/custom-plugins.md

clarify which index.jses

---

plugins/circleci/src/circleci-config.ts

cpp-844 make nightly setup dependent on checkout

---

core/cli/src/postInstall.ts
lib/types/src/npm.ts
plugins/circleci-npm/src/index.ts
plugins/npm/src/tasks/npm-publish.ts
plugins/npm/test/npm-publish.test.ts

cli core should not depend on plugins

move semVerRegex to types packages

---

plugins/heroku/src/setConfigVars.ts

Some of our [code](https://cs.github.com/?scopeName=All+repos&scope=&q=owner%3AFinancial-Times+NODE_ENV+branch) (even Tool Kit [itself](https://github.com/Financial-Times/dotcom-tool-kit/blob/7c0ed8895318e4803a83796efced50938609f2b4/plugins/upload-assets-to-s3/src/tasks/upload-assets-to-s3.ts#L37)!) expects review apps to have their `NODE_ENV` set to `branch` so that they can change behaviour for them (e.g., mocking out writes to production DB's.) `n-gage` would previously do this override [itself](https://github.com/Financial-Times/n-gage/blob/8b8ce6b01d9658b21a71e35e5cd3bfc8e35cb6cd/src/tasks/review-app.mk#L17). Rather than updating that assumption with a less magic check (somehow...) let's just do the same override in
the Tool Kit code.

Set NODE_ENV to 'branch' for review apps

---

.circleci/config.yml

build & test jobs are pointless, since they're still being run on the release-please PR and on tags

build: only run release-please job on main

---

plugins/pa11y/src/tasks/pa11y.ts

chore: release 0.1.0

---

.circleci/config.yml
core/sandbox/.circleci/config.yml
core/sandbox/package.json
package-lock.json
plugins/circleci/src/circleci-config.ts

This PR:
1. implements the new nightly workflows filtering config in toolkit circleci hooks
2. updates toolkit's circleci/config.yml as a result of running [update-config.ts](https://github.com/Financial-Times/platform-scripts/pull/16/files#diff-a7e8e598b9348de62c16c228519250d2fab44f26270628c91dff0ed52b7a1947R68) in platform scripts

Schedule pipelines

---

package-lock.json
package.json

The bug (https://github.com/googleapis/release-please/issues/1403) I'd made a fork for has now been fixed, along with another bug (https://github.com/googleapis/release-please/issues/1360) I'd reported!

Go back to the upstream release-please

---

plugins/pa11y/src/tasks/pa11y.ts

Also tried to improve the error messages a little bit

Fix Pa11y bug when running in CI

---

lib/logger/src/helpers.ts

call the original, unwrapped `stream.write` instead of the wrapper, which was previously being called because of pass by reference and mutability

fix: prevent infinite recursion when logging "["

---

plugins/husky-npm/src/index.ts

Allows use with commitlint and similar packages to run commands on commit messages with husky.
Example usage: https://github.com/Financial-Times/cp-content-pipeline/pull/18

Add commit message hook to husky plugin

---

lib/types/src/schema/node.ts
lib/types/src/schema/nodemon.ts
plugins/node/src/tasks/node.ts
plugins/nodemon/src/tasks/nodemon.ts

- allow running without Vault
- allow specifying what ports you want in options

more options for node & nodemon plugins

---

plugins/jest/readme.md

docs: added jest documentation

---

lib/types/src/schema/eslint.ts
plugins/eslint/package.json
plugins/eslint/readme.md
plugins/eslint/src/tasks/eslint.ts
plugins/eslint/test/tasks/eslint.test.ts

CPP-863 docs: add eslint readme.md

---

core/create/src/index.ts

The `create` package has some special handling for when the error being thrown is relating to Tool Kit conflicts. To check this we need to pull in a package defining the types from the local project rather than from a local Tool Kit installation (or a different version from the registry), as otherwise some of the instanceof checks won't work. So we import our `error` package before printing any errors.
However, sometimes that package won't be available as something failed before we could even finish an npm installation. In those cases it's safe to assume that the issue isn't related to Tool Kit conflicts as we haven't even installed Tool Kit yet, so if we can't import the `error` package let's assert this isn't related to conflicts. This allows us to print the actual error, rather than …

Handle npm installation failing in create script

---

plugins/mocha/readme.md

CPP-868: add readme for mocha plugin

---

plugins/nodemon/readme.md

Add readme for `@dotcom-tool-kit/nodemon` plugin.

CPP-872: add readme for nodemon plugin

---

plugins/n-test/README.md

CPP-869:Add n-test readme

---

package-lock.json
plugins/husky-npm/README.md

CPP-864: add husky npm readme

---

plugins/node/readme.md
readme.md

CPP-871: docs(node): add readme

---

docs/faq.md
readme.md

to answer general questions that aren't obviously covered elsewhere in the docs

CPP-1016: docs: add Tool Kit FAQ

---

lib/logger/src/helpers.ts

Based on https://financialtimes.slack.com/archives/C02TRE2V2Q1/p1655469494095279

Improve hookFook error message

---

plugins/prettier/readme.md
plugins/webpack/readme.md

docs: use standard table format for readme options

---

plugins/heroku/src/scaleDyno.ts

to disamabiguate when an app has multiple dynos

feat: log dyno type when scaling

---

plugins/serverless/readme.md

So we had a ticket to update the README for the serverless plugin but I think Jen mostly did that already as part of creating the first Serverless task. I've just tweaked the documentation a little to be as informative as the Heroku plugin is. Is there anything worth documenting here?

CPP-1055 Tidy up the documentation for Serverless

---

plugins/backend-serverless-app/package.json

fix: point backend-serverless-app package.json main field to a file that exists

---

orb/src/jobs/e2e-test-review.yml
orb/src/jobs/e2e-test-staging.yml

We want to store Cypress artifacts in CircleCi for debugging purposes.

chore: store e2e test artifacts in circleci

---

orb/src/@orb.yml

This addresses an issue with change logs not sending. [See this Slack message](https://financialtimes.slack.com/archives/C02FUPT6N/p1694095810202659).

fix: bump the Change API orb version

---

plugins/serverless/src/tasks/deploy.ts
plugins/serverless/src/tasks/provision.ts

The CI environment was overwriting the values needed for production / other remote environments.

CPP-1695: Serverless deploy prioritise env vars from secrets management service

---

plugins/upload-assets-to-s3/src/tasks/upload-assets-to-s3.ts
plugins/upload-assets-to-s3/test/tasks/upload-assets-to-s3.test.ts

This is to support the Doppler migration, as Doppler doesn't support secret names with lowercase characters.

CPP-1666 Try upper-cased secret names for AWS credentials to aid Doppler migration

---

core/create/src/prompts/conflicts.ts
core/create/src/prompts/options.ts
docs/migrating-to-tool-kit.md
lib/types/src/schema/heroku.ts

- makes docs a little more readable in a few places
- adds a conclude step to follow after migration is done
- points users to where to find details asked for in prompts

quick wins - cleanup prompts & documentation

---

lib/doppler/src/index.ts

Projects without an associated biz ops system [require](https://tech.in.ft.com/tech-topics/secrets-management/doppler/guide#repositories) a `repo_` prefix in their name. In the long run we want users to be fully migrating over to the `doppler` library and setting the project's name explicitly in its options, but for now when we're inferring the Doppler project name from the `vault` settings we should apply some heuristics to guess whether `repo_` needs to be prefixed to the Vault project name or not.

Guess when a Doppler project will require a repo_ prefix

---

core/cli/src/config.ts
core/cli/src/conflict.ts
core/cli/src/messages.ts

fixes a bug in the conflict message introduced by the lazy plugins refactor

fix conflict message

---

plugins/husky-npm/src/husky-hook.ts
plugins/husky-npm/src/index.ts

not deleting the plugin because i'll reimplement this hook using config in this plugin

chore!: delete the husky hook

---

lib/doppler/src/index.ts

This isn't possible because the Doppler CLI isn't installed on CI, and we don't want to give CircleCI an access token for Doppler. None of our plugins should be doing this at this point, but custom plugins might still be making this mistake.
We could also just return the empty object if the `environment` is CI as we often merge these secrets with `process.env` anyway, but I feel we should be louder that we shouldn't be trying to get Doppler secrets in CI?

Improve error message if you try to get Doppler secrets in CI

---

core/cli/src/config.ts
core/cli/src/index.ts
core/cli/src/install.ts
core/cli/src/plugin.ts
lib/types/src/base.ts
lib/types/src/validated.ts

refactor Validated to use chainable methods not nested function calls

---

core/cli/src/tasks.ts

oops
ig that just shows how long it is since i tried running it

fix: look in config.commandTasks for defined commands, not config.hooks 😅

---

core/create/src/prompts/confirmation.ts
core/create/src/prompts/main.ts
core/create/src/prompts/oidc.ts
core/create/src/prompts/options.ts
package-lock.json

Each fix is split into its own commit. Most of these bugs were found when we mobbed on migrating `next-test-sessions-lambda` to Tool Kit in the open hour. A few others are fixes to issues reported to us in #cp-platforms-team. The remainder are bugs I ran into when testing the other fixes!

CPP-1895 Various fixes to Tool Kit migration script

---

core/cli/src/install.ts

We've previously seen a few issues where tag filters were being added to the `waiting-for-approval job` incorrectly (we do not to wait for approval on releases.)
This was happening on some older repositories as they had an older version of Tool Kit installed that still used the `postInstall` function, which has since been [superseded by install state sharing](https://github.com/Financial-Times/dotcom-tool-kit/pull/299) and is deprecated. However, we saw this `postInstall` function was being run with newer versions of Tool Kit too, even though it's supposed to be [skipped](https://github.com/Financial-Times/dotcom-tool-kit/blob/1223562780bd18787b01421adb944615be5976a4/core/cli/src/install.ts#L66-L68)
if support for state sharing is detected. `postInstall` will unconditionally add the tag …

CPP-1428 Fix waiting-for-approval job sometimes running for release builds

---

core/cli/package.json
package-lock.json
plugins/package-json-hook/src/package-json-helper.ts

Reminds me of the old days of testing Tool Kit with next-static. 😰 At least I remembered to actually test the changes this time.

More fixes to unblock experiment-api

---

plugins/backend-app/package.json
plugins/backend-heroku-app/package.json
plugins/backend-serverless-app/package.json
plugins/circleci-deploy/package.json
plugins/circleci-heroku/package.json
plugins/circleci-npm/package.json
plugins/circleci/package.json
plugins/component/package.json
plugins/frontend-app/package.json

Bumping the next versions to include #662 .

Manually bump updated prerelease packages

---

plugins/typescript/package.json

feat(typescript): support typescript 5

---

scripts/create-plugin.js

build: update and simplify create-plugin script

---

plugins/circleci-npm/.toolkitrc.yml

https://financialtimes.slack.com/archives/C02TRE2V2Q1/p1727354801166279

fix: don't split publish-tag into matrix

---

orb/src/jobs/deploy-production.yml
orb/src/jobs/deploy-review.yml
orb/src/jobs/deploy-staging.yml

We need the `docker` command to be available for deployment tasks please. We'll be writing a Docker plugin later and will chat to you about the implementation then, in the meantime it'd be useful if we didn't have to rely on a test build of the orb.
---
See-also: [CPREL-1209](https://financialtimes.atlassian.net/browse/CPREL-1209)
[CPREL-1209]: https://financialtimes.atlassian.net/browse/CPREL-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add docker to deploys

---

lib/schemas/src/plugins.ts

fix(schema): correct suggested task name for eslint options

---

docs/migration-guides/v4.md
readme.md

V4 migration guide

---

core/cli/package.json
core/cli/src/config.ts
core/cli/src/messages.ts
core/cli/src/plugin/options.ts
docs/migration-guides/v4.md
package-lock.json

friendlier and more readable option validation messages

---

core/cli/src/fetch.ts
core/cli/src/tasks.ts

Fix native fetch

---

core/cli/src/plugin/entry-point.ts

in #736 we switch from `import` to `require`. previously, `import` had been compiled to `require` with a compiled-ESM-compatibility helper function to set `defaults` to the `module.exports`. with a plain `require`, this isn't happening, so CJS custom plugins that use `module.exports` don't load.
use the `__importDefault` helper from `tslib` so we can load both CJS-compiled-ESM (from built-in plugins) and plain CJS (from custom plugins).

fix: actually support CJS in importEntryPoint

---

core/cli/src/messages.ts
lib/base/package.json
package-lock.json

Reported by @Nazehs: https://financialtimes.slack.com/archives/C3TJ6KXEU/p1736428881082699. Both issues I found were related to npm not hoisting packages like we'd expect 😅

Fix issues found whilst migrating next-test-user-service-api to Tool Kit v4

---

plugins/docker/src/tasks/build.ts

You can't use the default `docker build` to build multi-arch images, this is something we need if we want to build ARM-based images in CircleCI. The alternative would be to move _all_ our CircleCI jobs to ARM which is more expensive and a bunch of work.
I tested this on our migration canary:
* [Here's the relevant code that ran successfully](https://github.com/Financial-Times/cp-docker-migration-canary/commit/7108fc6003279a3eb5b5a0a4c5c14f805fc0bfaf)
* [Here's the built image, note that it's ARM](https://cloudsmith.io/~financial-times/repos/cp-container-registry/packages/detail/docker/cp-docker-migration-canary/1ac7d058f41dd8d820f00fb50bd9f14611c981c6f465d5cde772edc04f2afd57/a=arm64;xpo=linux/)

fix: allow building ARM64 images in AMD CI jobs

---

package-lock.json
plugins/containerised-app/.toolkitrc.yml
plugins/containerised-app/package.json

We missed this one out, sorry.

fix: depend on the circleci-deploy plugin

---

plugins/hako/src/tasks/deploy.ts

fix: upgrade hako to v0.1.11-alpha

---

plugins/containerised-app-with-assets/package.json
plugins/containerised-app/package.json

Oops! Not at all sure how we missed this.

fix: include schema file in published package

---

plugins/hako/src/tasks/deploy.ts

We're intending on adding some more complexity to this, adding the ability to deploy an ephemeral (review) app and streaming a file into the `stdin` of this `docker run`. This will require some more async code and some error handling.
Because of this it makes sense to bundle it all into a single async function rather than only putting the `waitOnExit` into our array of promises.
Another PR will land soon to do the rest of the work and it'll be easier to review because of this 😁

refactor: move hako deploy running into a method

---

plugins/hako/src/tasks/deploy.ts

This allows us to deploy worker processes.

feat: update hako to v0.2.4-beta

---

core/cli/package.json
package-lock.json
plugins/heroku/package.json
plugins/webpack/package.json

Dependabot is good at pointing out dependencies we either installed accidentally or no longer use!

Remove more unused dependencies

---

plugins/hako/src/tasks/deploy.ts

feat: update hako CLI to v0.2.7-beta

---

core/cli/src/messages.ts
plugins/docker/readme.md

Add a note about yaml indentation to improve the ease of debugging.

Docs: add note on indentation

---

package-lock.json
plugins/n-test/package.json

This allows us to use ESM config files.

feat: upgrade n-test to v8.1.0
